"""Generate deterministic RTL simulation fixtures for Phase 0."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

from npu_assembler.phase0 import encode_program, encode_uop

from .compiler import compile_graph
from .golden import matmul


DEFAULT_GRAPH_PATH = Path("test/graphs/matmul_softmax.json")
DEFAULT_INPUTS_PATH = Path("test/inputs/matmul_softmax.json")
TB_SPEC_INCLUDE = "npu_v0_spec.svh"
TB_FIXTURE_INCLUDE = "npu_v0_tb_params.svh"


def generate_default_fixtures(
    out_dir: Path,
    arch: dict[str, Any],
    graph_path: Path = DEFAULT_GRAPH_PATH,
    inputs_path: Path = DEFAULT_INPUTS_PATH,
) -> None:
    """Emit compiled RTL fixtures under ``out_dir``."""

    out_dir.mkdir(parents=True, exist_ok=True)

    graph = _read_json(graph_path)
    inputs = _read_json(inputs_path)
    matmul_op = _first_op(graph, "matmul")
    a = inputs[matmul_op["a"]]
    b = inputs[matmul_op["b"]]
    c = matmul(a, b)
    x = c[0]
    y = softmax_q0_8(x)
    matmul_count = len(_flatten(c))
    softmax_count = len(y)

    _write_hex(out_dir / "matmul_a.hex", _flatten(a), 2)
    _write_hex(out_dir / "matmul_b.hex", _flatten(b), 2)
    _write_hex(out_dir / "matmul_expected_c.hex", _flatten(c), 8)
    matmul_artifact = compile_graph(_single_op_graph(graph, matmul_op), arch)
    _write_hex(
        out_dir / "matmul_program.hex",
        _pad_program(encode_program(matmul_artifact["program"], arch), arch),
        8,
    )

    _write_hex(out_dir / "softmax_x.hex", x, 2)
    _write_hex(out_dir / "softmax_expected_y.hex", y, 2)
    softmax_artifact = compile_graph(
        {
            "tensors": {
                "X": {"shape": [1, arch["rtl"]["softmax_vector_len"]], "dtype": "int8"},
            },
            "ops": [{"type": "softmax", "x": "X", "out": "Y"}],
        },
        arch,
    )
    _write_hex(
        out_dir / "softmax_program.hex",
        _pad_program(encode_program(softmax_artifact["program"], arch), arch),
        8,
    )
    _write_sv_spec_include(out_dir / TB_SPEC_INCLUDE, arch)
    _write_sv_tb_fixture_include(
        out_dir / TB_FIXTURE_INCLUDE,
        out_dir,
        matmul_count,
        softmax_count,
    )


def softmax_q0_8(values: list[int]) -> list[int]:
    """Match the tiny integer softmax approximation in ``npu_v0_compute_cluster.sv``."""

    max_v = max(values)
    exp_values = [_exp_lut_q8(v - max_v) for v in values]
    denom = sum(exp_values)
    if denom == 0:
        return [0 for _ in values]
    return [((v * 255) // denom) & 0xFF for v in exp_values]


def _exp_lut_q8(delta: int) -> int:
    if delta >= 0:
        return 255
    return {
        -1: 94,
        -2: 35,
        -3: 13,
        -4: 5,
        -5: 2,
        -6: 1,
    }.get(delta, 0)


def _flatten(matrix: list[list[int]]) -> list[int]:
    return [value for row in matrix for value in row]


def _pad_program(program: list[int], arch: dict[str, Any], depth: int = 16) -> list[int]:
    if len(program) > depth:
        raise ValueError(f"program length {len(program)} exceeds RTL instruction depth {depth}")
    return program + [encode_uop(arch, "HALT")] * (depth - len(program))


def _lookup_encoding(values: dict[str, int], name: str) -> int:
    if name not in values:
        raise ValueError(f"missing ISA encoding for {name!r}")
    return values[name]


def _write_hex(path: Path, values: Iterable[int], width: int) -> None:
    mask = (1 << (width * 4)) - 1
    with path.open("w", encoding="utf-8") as f:
        for value in values:
            f.write(f"{int(value) & mask:0{width}x}\n")


def _write_sv_spec_include(path: Path, arch: dict[str, Any]) -> None:
    encoding = arch["isa"]["encoding"]
    host_map = arch["rtl"]["host_map"]
    control_bits = arch["rtl"]["control_bits"]
    lines = [
        "// Generated by npu_phase0.rtl_fixture from arch/configs/npu_v0.jsonc.",
        "// Do not edit by hand.",
        f"localparam int UOP_WORD_BITS = {encoding['word_bits']};",
        f"localparam int RTL_MATMUL_M = {arch['rtl']['matmul_tile'][0]};",
        f"localparam int RTL_MATMUL_N = {arch['rtl']['matmul_tile'][1]};",
        f"localparam int RTL_MATMUL_K = {arch['rtl']['matmul_tile'][2]};",
        "localparam int RTL_MATMUL_ELEMS = RTL_MATMUL_M * RTL_MATMUL_N;",
        f"localparam int RTL_SOFTMAX_LEN = {arch['rtl']['softmax_vector_len']};",
        _sv_field_param("UOP_OPCODE", encoding["opcode"]),
        _sv_field_param("UOP_ARG0", encoding["arg0"]),
        _sv_field_param("UOP_ARG1", encoding["arg1"]),
    ]
    for op, value in encoding["opcodes"].items():
        lines.append(f"localparam [3:0] UOP_{op} = 4'h{value:x};")
    for tensor, value in encoding["tensors"].items():
        lines.append(f"localparam [3:0] TENSOR_{tensor} = 4'h{value:x};")
    for buffer, value in encoding["buffers"].items():
        lines.append(f"localparam [3:0] BUF_{_sv_name(buffer)} = 4'h{value:x};")
    for name, window in host_map.items():
        prefix = f"RTL_HOST_{_sv_name(name)}"
        lines.append(f"localparam logic [11:0] {prefix}_BASE = 12'h{int(window['base_word']):03x};")
        lines.append(f"localparam int {prefix}_WORDS = {int(window['words'])};")
    for name, bit in control_bits.items():
        lines.append(f"localparam int RTL_CTRL_{_sv_name(name)}_BIT = {int(bit)};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_sv_tb_fixture_include(
    path: Path,
    out_dir: Path,
    matmul_count: int,
    softmax_count: int,
) -> None:
    base = out_dir.as_posix()
    lines = [
        "// Generated by npu_phase0.rtl_fixture. Do not edit by hand.",
        f'localparam string MATMUL_A_HEX = "{base}/matmul_a.hex";',
        f'localparam string MATMUL_B_HEX = "{base}/matmul_b.hex";',
        f'localparam string MATMUL_PROGRAM_HEX = "{base}/matmul_program.hex";',
        f'localparam string MATMUL_EXPECTED_C_HEX = "{base}/matmul_expected_c.hex";',
        f'localparam string SOFTMAX_X_HEX = "{base}/softmax_x.hex";',
        f'localparam string SOFTMAX_PROGRAM_HEX = "{base}/softmax_program.hex";',
        f'localparam string SOFTMAX_EXPECTED_Y_HEX = "{base}/softmax_expected_y.hex";',
        f"localparam int MATMUL_OUTPUT_COUNT = {matmul_count};",
        f"localparam int SOFTMAX_OUTPUT_COUNT = {softmax_count};",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _sv_field_param(prefix: str, field: dict[str, int]) -> str:
    return f"localparam int {prefix}_MSB = {field['msb']}, {prefix}_LSB = {field['lsb']};"


def _sv_name(name: str) -> str:
    return name.upper()


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _first_op(graph: dict[str, Any], op_type: str) -> dict[str, Any]:
    for op in graph.get("ops", []):
        if op.get("type") == op_type:
            return op
    raise ValueError(f"graph does not contain op type {op_type!r}")


def _single_op_graph(graph: dict[str, Any], op: dict[str, Any]) -> dict[str, Any]:
    if op["type"] != "matmul":
        raise ValueError("only matmul single-op graph extraction is supported")
    return {
        "tensors": {
            op["a"]: graph["tensors"][op["a"]],
            op["b"]: graph["tensors"][op["b"]],
        },
        "ops": [op],
    }
