"""Generate deterministic RTL simulation fixtures for Phase 0."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

from npu_assembler.phase0 import encode_program, encode_uop
from npu_compiler.attention import build_softmax_expanded_primitive_program

from .compiler import compile_graph
from .golden import matmul


DEFAULT_GRAPH_PATH = Path("test/graphs/matmul.json")
DEFAULT_INPUTS_PATH = Path("test/inputs/matmul.json")
TB_SPEC_INCLUDE = "npu_v0_spec.svh"
TB_FIXTURE_INCLUDE = "npu_v0_tb_params.svh"


def generate_default_fixtures(
    out_dir: Path,
    arch: dict[str, Any],
    graph_path: Path = DEFAULT_GRAPH_PATH,
    inputs_path: Path = DEFAULT_INPUTS_PATH,
) -> None:
    """Emit compiled RTL fixtures under ``out_dir``."""

    out_dir.mkdir(parents=True, exist_ok=True)

    graph = _read_json(graph_path)
    inputs = _read_json(inputs_path)
    matmul_op = _first_op(graph, "matmul")
    a = inputs[matmul_op["a"]]
    b = inputs[matmul_op["b"]]
    c = matmul(a, b)
    matmul_count = len(_flatten(c))

    _write_hex(out_dir / "matmul_a.hex", _flatten(a), 2)
    _write_hex(out_dir / "matmul_b.hex", _flatten(b), 2)
    _write_hex(out_dir / "matmul_expected_c.hex", _flatten(c), 8)
    matmul_artifact = compile_graph(_single_op_graph(graph, matmul_op), arch)
    _write_hex(
        out_dir / "matmul_program.hex",
        _pad_program(encode_program(matmul_artifact["program"], arch), arch),
        8,
    )

    _write_hex(
        out_dir / "attention_scale_mask_program.hex",
        _pad_program(
            [
                encode_uop(arch, "VSCALE_FIXED", row)
                for row in range(arch["rtl"]["softmax_vector_len"])
            ]
            + [encode_uop(arch, "HALT")],
            arch,
        ),
        8,
    )
    attention_softmax_program = build_softmax_expanded_primitive_program(
        rows=arch["rtl"]["softmax_vector_len"],
        elements=arch["rtl"]["softmax_vector_len"],
        capacity_words=arch["rtl"]["host_map"]["program"]["words"],
    )
    _write_hex(
        out_dir / "attention_softmax_program.hex",
        [_encode_attention_softmax_uop(arch, inst) for inst in attention_softmax_program["program"]],
        8,
    )
    _write_sv_spec_include(out_dir / TB_SPEC_INCLUDE, arch)
    _write_sv_tb_fixture_include(
        out_dir / TB_FIXTURE_INCLUDE,
        out_dir,
        matmul_count,
    )


def _flatten(matrix: list[list[int]]) -> list[int]:
    return [value for row in matrix for value in row]


def _pad_program(program: list[int], arch: dict[str, Any], depth: int = 16) -> list[int]:
    if len(program) > depth:
        raise ValueError(f"program length {len(program)} exceeds RTL instruction depth {depth}")
    return program + [encode_uop(arch, "HALT")] * (depth - len(program))


def _lookup_encoding(values: dict[str, int], name: str) -> int:
    if name not in values:
        raise ValueError(f"missing ISA encoding for {name!r}")
    return values[name]


def _write_hex(path: Path, values: Iterable[int], width: int) -> None:
    mask = (1 << (width * 4)) - 1
    with path.open("w", encoding="utf-8") as f:
        for value in values:
            f.write(f"{int(value) & mask:0{width}x}\n")


def _write_sv_spec_include(path: Path, arch: dict[str, Any]) -> None:
    encoding = arch["isa"]["encoding"]
    host_map = arch["rtl"]["host_map"]
    control_bits = arch["rtl"]["control_bits"]
    perf_contract = arch["performance_contract"]
    accumulator = perf_contract["accumulator"]
    attention_row = perf_contract["attention_row_storage"]
    matrix_feed = perf_contract["matrix_operand_feed"]
    lines = [
        "// Generated by npu_phase0.rtl_fixture from arch/configs/npu_v0.jsonc.",
        "// Do not edit by hand.",
        f"localparam int UOP_WORD_BITS = {encoding['word_bits']};",
        f"localparam int RTL_MATMUL_M = {arch['rtl']['matmul_tile'][0]};",
        f"localparam int RTL_MATMUL_N = {arch['rtl']['matmul_tile'][1]};",
        f"localparam int RTL_MATMUL_K = {arch['rtl']['matmul_tile'][2]};",
        "localparam int RTL_MATMUL_ELEMS = RTL_MATMUL_M * RTL_MATMUL_N;",
        f"localparam int RTL_SOFTMAX_LEN = {arch['rtl']['softmax_vector_len']};",
        f"localparam int RTL_PERF_ACC_ELEMENTS = {accumulator['elements']};",
        f"localparam int RTL_PERF_ACC_CLEAR_ELEMENTS_PER_CYCLE = {accumulator['clear_elements_per_cycle']};",
        f"localparam int RTL_PERF_ACC_COMMIT_ELEMENTS_PER_CYCLE = {accumulator['commit_elements_per_cycle']};",
        f"localparam int RTL_PERF_ACC_READOUT_ELEMENTS_PER_CYCLE = {accumulator['readout_elements_per_cycle']};",
        f"localparam int RTL_PERF_ACC_CLEAR_CYCLES = {accumulator['clear_cycles']};",
        f"localparam int RTL_PERF_ACC_COMMIT_CYCLES = {accumulator['commit_cycles']};",
        f"localparam int RTL_PERF_ACC_READOUT_CYCLES = {accumulator['readout_cycles']};",
        f"localparam int RTL_PERF_ACC_COMMIT_ADD_LANES = {accumulator['commit_add_lanes']};",
        f"localparam int RTL_PERF_ACC_READ_BUS_BITS = {accumulator['read_bus_bits']};",
        f"localparam int RTL_PERF_ACC_WRITE_BUS_BITS = {accumulator['write_bus_bits']};",
        f"localparam int RTL_PERF_ATTN_ROW_ELEMENTS = {attention_row['elements_per_row']};",
        f"localparam int RTL_PERF_ATTN_ROW_READ_ELEMENTS_PER_CYCLE = {attention_row['read_elements_per_cycle']};",
        f"localparam int RTL_PERF_ATTN_ROW_WRITE_ELEMENTS_PER_CYCLE = {attention_row['write_elements_per_cycle']};",
        f"localparam int RTL_PERF_MATRIX_A_ELEMENTS_PER_CYCLE = {matrix_feed['a_elements_per_cycle']};",
        f"localparam int RTL_PERF_MATRIX_B_ELEMENTS_PER_CYCLE = {matrix_feed['b_elements_per_cycle']};",
        f"localparam logic signed [31:0] RTL_SCORE_SCALE_MULTIPLIER = 32'sd{arch['vector_sfu']['score_scale_multiplier']};",
        f"localparam logic [4:0] RTL_SCORE_SCALE_SHIFT = 5'd{arch['vector_sfu']['score_scale_shift']};",
        f"localparam logic signed [31:0] RTL_SOFTMAX_NEG_INF = {_sv_signed_decimal(arch['vector_sfu']['softmax_neg_inf'], 32)};",
        f"localparam logic signed [31:0] RTL_SOFTMAX_CLAMP_LOW = {_sv_signed_decimal(arch['vector_sfu']['softmax_clamp_low'], 32)};",
        f"localparam logic signed [31:0] RTL_SOFTMAX_CLAMP_HIGH = {_sv_signed_decimal(arch['vector_sfu']['softmax_clamp_high'], 32)};",
        f"localparam logic [4:0] RTL_SOFTMAX_NORMALIZE_SHIFT = 5'd{arch['vector_sfu']['softmax_normalize_shift']};",
        f"localparam int RTL_SFU_EXP_INPUT_SCALE = {arch['vector_sfu']['sfu_exp_input_scale']};",
        f"localparam int RTL_SFU_EXP_LUT_ENTRIES = {arch['vector_sfu']['sfu_exp_lut_entries']};",
        f"localparam int RTL_SFU_EXP_OUTPUT_Q = {arch['vector_sfu']['sfu_exp_output_q']};",
        f"localparam int RTL_SFU_RECIP_OUTPUT_Q = {arch['vector_sfu']['sfu_recip_output_q']};",
        f"localparam int RTL_SFU_RSQRT_OUTPUT_Q = {arch['vector_sfu']['sfu_rsqrt_output_q']};",
        _sv_field_param("UOP_OPCODE", encoding["opcode"]),
        _sv_field_param("UOP_ARG0", encoding["arg0"]),
        _sv_field_param("UOP_ARG1", encoding["arg1"]),
    ]
    for op, value in encoding["opcodes"].items():
        lines.append(f"localparam [3:0] UOP_{op} = 4'h{value:x};")
    for idx, value in enumerate(arch["vector_sfu"]["sfu_bringup_exp_q15_segments"]):
        lines.append(f"localparam int RTL_SFU_BRINGUP_EXP_SEG_{idx} = {int(value)};")
    for tensor, value in encoding["tensors"].items():
        lines.append(f"localparam [3:0] TENSOR_{tensor} = 4'h{value:x};")
    for buffer, value in encoding["buffers"].items():
        lines.append(f"localparam [3:0] BUF_{_sv_name(buffer)} = 4'h{value:x};")
    for group, prefix in (
        ("command_events", "TRACE_CMD"),
        ("scheduler_wait_reasons", "TRACE_SCHED_WAIT"),
        ("compute_control_events", "TRACE_COMPUTE_CTRL"),
    ):
        for name, value in arch["trace_contract"][group].items():
            lines.append(f"localparam logic [3:0] {prefix}_{_sv_name(name)} = 4'd{int(value)};")
    for name, window in host_map.items():
        prefix = f"RTL_HOST_{_sv_name(name)}"
        lines.append(f"localparam logic [11:0] {prefix}_BASE = 12'h{int(window['base_word']):03x};")
        lines.append(f"localparam int {prefix}_WORDS = {int(window['words'])};")
    for name, bit in control_bits.items():
        lines.append(f"localparam int RTL_CTRL_{_sv_name(name)}_BIT = {int(bit)};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _encode_attention_softmax_uop(arch: dict[str, Any], inst: dict[str, Any]) -> int:
    op_map = {
        "REDUCE_MAX": "VREDMAX",
        "VEC_SUB": "VSUB",
        "VEC_CLAMP": "VCLAMP",
        "SFU_EXP": "VEXP",
        "REDUCE_SUM": "VREDSUM",
        "SFU_RECIP": "VDIV",
        "VEC_SCALE": "VNORM",
        "HALT": "HALT",
    }
    opcode = op_map[inst["op"]]
    return encode_uop(arch, opcode, int(inst.get("row", 0)), int(inst.get("lane", 0)))


def _sv_signed_decimal(value: int, width: int) -> str:
    value = int(value)
    return f"-{width}'sd{-value}" if value < 0 else f"{width}'sd{value}"


def _write_sv_tb_fixture_include(
    path: Path,
    out_dir: Path,
    matmul_count: int,
) -> None:
    base = out_dir.as_posix()
    lines = [
        "// Generated by npu_phase0.rtl_fixture. Do not edit by hand.",
        f'localparam string MATMUL_A_HEX = "{base}/matmul_a.hex";',
        f'localparam string MATMUL_B_HEX = "{base}/matmul_b.hex";',
        f'localparam string MATMUL_PROGRAM_HEX = "{base}/matmul_program.hex";',
        f'localparam string MATMUL_EXPECTED_C_HEX = "{base}/matmul_expected_c.hex";',
        f"localparam int MATMUL_OUTPUT_COUNT = {matmul_count};",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _sv_field_param(prefix: str, field: dict[str, int]) -> str:
    return f"localparam int {prefix}_MSB = {field['msb']}, {prefix}_LSB = {field['lsb']};"


def _sv_name(name: str) -> str:
    return name.upper()


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _first_op(graph: dict[str, Any], op_type: str) -> dict[str, Any]:
    for op in graph.get("ops", []):
        if op.get("type") == op_type:
            return op
    raise ValueError(f"graph does not contain op type {op_type!r}")


def _single_op_graph(graph: dict[str, Any], op: dict[str, Any]) -> dict[str, Any]:
    if op["type"] != "matmul":
        raise ValueError("only matmul single-op graph extraction is supported")
    return {
        "tensors": {
            op["a"]: graph["tensors"][op["a"]],
            op["b"]: graph["tensors"][op["b"]],
        },
        "ops": [op],
    }
