"""Emit generated headers from the SoC JSONC spec."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--soc", type=Path, default=Path("arch/configs/soc_v0.jsonc"))
    parser.add_argument("--out", type=Path, default=Path("build/soc/soc_v0_addr.svh"))
    parser.add_argument("--header-out", type=Path, default=Path("build/soc/soc_v0_addr.h"))
    parser.add_argument("--linker-out", type=Path, default=Path("build/soc/soc_v0.ld"))
    args = parser.parse_args()

    spec = _read_jsonc(args.soc)
    memory_map = spec["memory_map"]
    _validate_memory_map(memory_map)
    entries = [
        ("SOC_CPU_RESET_VECTOR", spec["cpu"]["reset_vector"]),
        ("SOC_CPU_STACK_POINTER", spec["cpu"]["stack_pointer"]),
    ]
    bus_entries = _bus_entries(spec.get("bus", {}))
    entries.extend(bus_entries)
    mover_entries = _npu_data_mover_entries(spec.get("npu_data_mover", {}))
    entries.extend(mover_entries)
    for name in ("boot_rom", "sram", "npu_wrapper", "uart", "test_status"):
        region = memory_map[name]
        prefix = f"SOC_{name.upper()}"
        base = region["base"]
        size = region["size_bytes"]
        entries.append((f"{prefix}_BASE", base))
        entries.append((f"{prefix}_SIZE_BYTES", size))
        entries.append((f"{prefix}_MASK", _mask_for_size(size)))

    npu_job_desc = spec.get("abi", {}).get("npu_job_desc", {})
    desc_entries, desc_fields = _npu_job_desc_entries(npu_job_desc)
    entries.extend(desc_entries)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(_emit_svh(entries), encoding="utf-8")
    args.header_out.parent.mkdir(parents=True, exist_ok=True)
    args.header_out.write_text(_emit_header(entries, desc_fields), encoding="utf-8")
    args.linker_out.parent.mkdir(parents=True, exist_ok=True)
    args.linker_out.write_text(_emit_linker_script(memory_map), encoding="utf-8")


def _emit_svh(entries: list[tuple[str, int]]) -> str:
    lines = [
        "// Generated by sw/tools/soc/emit_soc_spec.py from arch/configs/soc_v0.jsonc.",
        "// Do not edit by hand.",
    ]
    max_name = max(len(name) for name, _value in entries)
    for name, value in entries:
        lines.append(f"localparam logic [31:0] {name:<{max_name}} = 32'h{value & 0xFFFF_FFFF:08x};")
    return "\n".join(lines) + "\n"


def _emit_header(entries: list[tuple[str, int]], desc_fields: list[dict[str, Any]]) -> str:
    lines = [
        "/* Generated by sw/tools/soc/emit_soc_spec.py from arch/configs/soc_v0.jsonc. */",
        "/* Do not edit by hand. */",
        "#ifndef SOC_V0_ADDR_H",
        "#define SOC_V0_ADDR_H",
        "",
        "#ifndef __ASSEMBLER__",
        "#include <stdint.h>",
        "#endif",
        "",
    ]
    max_name = max(len(name) for name, _value in entries)
    for name, value in entries:
        lines.append(f"#define {name:<{max_name}} 0x{value & 0xFFFF_FFFF:08x}u")
    if desc_fields:
        lines.extend(["", "#ifndef __ASSEMBLER__", "typedef struct {"])
        for field in sorted(desc_fields, key=lambda item: int(item["word"])):
            lines.append(f"    uint32_t {field['name']};")
        lines.extend(["} soc_npu_job_desc_t;", "#endif"])
    lines.extend(["", "#endif"])
    return "\n".join(lines) + "\n"


def _npu_job_desc_entries(npu_job_desc: dict[str, Any]) -> tuple[list[tuple[str, int]], list[dict[str, Any]]]:
    if not npu_job_desc:
        return [], []

    fields = list(npu_job_desc["fields"])
    op_types = npu_job_desc["op_types"]
    _validate_npu_job_desc(fields)

    entries: list[tuple[str, int]] = [("SOC_NPU_JOB_DESC_WORDS", len(fields))]
    for field in sorted(fields, key=lambda item: int(item["word"])):
        entries.append((f"SOC_NPU_JOB_DESC_{field['name'].upper()}_WORD", int(field["word"])))
    for name, value in op_types.items():
        entries.append((f"SOC_NPU_JOB_OP_{name.upper()}", int(value)))
    return entries, fields


def _validate_npu_job_desc(fields: list[dict[str, Any]]) -> None:
    words = sorted(int(field["word"]) for field in fields)
    expected = list(range(len(fields)))
    if words != expected:
        raise ValueError(f"npu_job_desc words must be contiguous from 0: got {words}")


def _bus_entries(bus: dict[str, Any]) -> list[tuple[str, int]]:
    addr_width = int(bus.get("addr_width_bits", 32))
    data_width = int(bus.get("data_width_bits", 32))
    sram_cpu_lanes = int(bus.get("sram_cpu_lanes", 1))
    sram_cpu_data_width = int(bus.get("sram_cpu_data_width_bits", sram_cpu_lanes * data_width))
    if addr_width != 32:
        raise ValueError(f"only 32-bit SoC addresses are supported today: {addr_width}")
    if data_width != 32:
        raise ValueError(f"the PicoRV32 CPU bus must remain 32-bit today: {data_width}")
    if sram_cpu_lanes <= 0:
        raise ValueError(f"sram_cpu_lanes must be positive: {sram_cpu_lanes}")
    if sram_cpu_data_width != sram_cpu_lanes * 32:
        raise ValueError(
            "sram_cpu_data_width_bits must equal sram_cpu_lanes * 32: "
            f"{sram_cpu_data_width} != {sram_cpu_lanes * 32}"
        )
    return [
        ("SOC_BUS_ADDR_WIDTH_BITS", addr_width),
        ("SOC_BUS_DATA_WIDTH_BITS", data_width),
        ("SOC_SRAM_CPU_LANES", sram_cpu_lanes),
        ("SOC_SRAM_CPU_DATA_WIDTH_BITS", sram_cpu_data_width),
    ]


def _npu_data_mover_entries(mover: dict[str, Any]) -> list[tuple[str, int]]:
    if not mover:
        return []
    core_host_lanes = int(mover["core_host_lanes"])
    sram_npu_lanes = int(mover["sram_npu_lanes"])
    words_per_cycle = int(mover["words_per_cycle"])
    setup_cycles = int(mover.get("setup_cycles", 0))
    if core_host_lanes <= 0 or sram_npu_lanes <= 0:
        raise ValueError("npu_data_mover lanes must be positive")
    if core_host_lanes != sram_npu_lanes:
        raise ValueError("current RTL requires core_host_lanes == sram_npu_lanes")
    max_words = min(core_host_lanes, sram_npu_lanes)
    if words_per_cycle <= 0 or words_per_cycle > max_words:
        raise ValueError(
            "npu_data_mover.words_per_cycle must be in "
            f"1..min(core_host_lanes, sram_npu_lanes), got {words_per_cycle}"
        )
    if setup_cycles < 0:
        raise ValueError(f"npu_data_mover.setup_cycles must be non-negative: {setup_cycles}")
    return [
        ("SOC_NPU_CORE_HOST_LANES", core_host_lanes),
        ("SOC_NPU_SRAM_LANES", sram_npu_lanes),
        ("SOC_NPU_DATA_MOVER_WORDS_PER_CYCLE", words_per_cycle),
        ("SOC_NPU_DATA_MOVER_SETUP_CYCLES", setup_cycles),
    ]


def _emit_linker_script(memory_map: dict[str, Any]) -> str:
    rom = memory_map["boot_rom"]
    sram = memory_map["sram"]
    return "\n".join(
        [
            "/* Generated by sw/tools/soc/emit_soc_spec.py from arch/configs/soc_v0.jsonc. */",
            "/* Do not edit by hand. */",
            "ENTRY(_start)",
            "",
            "MEMORY",
            "{",
            f"    ROM  (rx)  : ORIGIN = 0x{rom['base'] & 0xFFFF_FFFF:08x}, LENGTH = 0x{rom['size_bytes']:08x}",
            f"    SRAM (rwx) : ORIGIN = 0x{sram['base'] & 0xFFFF_FFFF:08x}, LENGTH = 0x{sram['size_bytes']:08x}",
            "}",
            "",
            "SECTIONS",
            "{",
            "    .text : {",
            "        KEEP(*(.text.start))",
            "        *(.text*)",
            "        *(.rodata*)",
            "    } > ROM",
            "",
            "    .data : {",
            "        *(.data*)",
            "    } > SRAM AT > ROM",
            "",
            "    .bss (NOLOAD) : {",
            "        *(.bss*)",
            "        *(COMMON)",
            "    } > SRAM",
            "}",
            "",
        ]
    )


def _mask_for_size(size: int) -> int:
    if size <= 0 or size & (size - 1):
        raise ValueError(f"region size must be a positive power of two: {size}")
    return (0x1_0000_0000 - size) & 0xFFFF_FFFF


def _validate_memory_map(memory_map: dict[str, Any]) -> None:
    for name, region in memory_map.items():
        base = int(region["base"])
        size = int(region["size_bytes"])
        if size <= 0 or size & (size - 1):
            raise ValueError(f"{name} size must be a positive power of two: {size}")
        if base % size != 0:
            raise ValueError(f"{name} base 0x{base:08x} must be aligned to size 0x{size:08x}")


def _read_jsonc(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    lines = [_strip_line_comment(line) for line in text.splitlines()]
    return json.loads("\n".join(lines))


def _strip_line_comment(line: str) -> str:
    in_string = False
    escaped = False
    for i in range(len(line) - 1):
        ch = line[i]
        if escaped:
            escaped = False
            continue
        if ch == "\\":
            escaped = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if not in_string and line[i : i + 2] == "//":
            return line[:i]
    return line


if __name__ == "__main__":
    main()
