"""Emit generated headers from the SoC JSONC spec."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--soc", type=Path, default=Path("arch/configs/soc_v0.jsonc"))
    parser.add_argument("--out", type=Path, default=Path("build/soc/soc_v0_addr.svh"))
    parser.add_argument("--header-out", type=Path, default=Path("build/soc/soc_v0_addr.h"))
    parser.add_argument("--linker-out", type=Path, default=Path("build/soc/soc_v0.ld"))
    args = parser.parse_args()

    spec = _read_jsonc(args.soc)
    memory_map = spec["memory_map"]
    _validate_memory_map(memory_map)
    entries = [
        ("SOC_CPU_RESET_VECTOR", spec["cpu"]["reset_vector"]),
        ("SOC_CPU_STACK_POINTER", spec["cpu"]["stack_pointer"]),
    ]
    for name in ("boot_rom", "sram", "npu_wrapper", "uart", "test_status"):
        region = memory_map[name]
        prefix = f"SOC_{name.upper()}"
        base = region["base"]
        size = region["size_bytes"]
        entries.append((f"{prefix}_BASE", base))
        entries.append((f"{prefix}_SIZE_BYTES", size))
        entries.append((f"{prefix}_MASK", _mask_for_size(size)))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(_emit_svh(entries), encoding="utf-8")
    args.header_out.parent.mkdir(parents=True, exist_ok=True)
    args.header_out.write_text(_emit_header(entries), encoding="utf-8")
    args.linker_out.parent.mkdir(parents=True, exist_ok=True)
    args.linker_out.write_text(_emit_linker_script(memory_map), encoding="utf-8")


def _emit_svh(entries: list[tuple[str, int]]) -> str:
    lines = [
        "// Generated by sw/tools/soc/emit_soc_spec.py from arch/configs/soc_v0.jsonc.",
        "// Do not edit by hand.",
    ]
    max_name = max(len(name) for name, _value in entries)
    for name, value in entries:
        lines.append(f"localparam logic [31:0] {name:<{max_name}} = 32'h{value & 0xFFFF_FFFF:08x};")
    return "\n".join(lines) + "\n"


def _emit_header(entries: list[tuple[str, int]]) -> str:
    lines = [
        "/* Generated by sw/tools/soc/emit_soc_spec.py from arch/configs/soc_v0.jsonc. */",
        "/* Do not edit by hand. */",
        "#ifndef SOC_V0_ADDR_H",
        "#define SOC_V0_ADDR_H",
        "",
    ]
    max_name = max(len(name) for name, _value in entries)
    for name, value in entries:
        lines.append(f"#define {name:<{max_name}} 0x{value & 0xFFFF_FFFF:08x}u")
    lines.extend(["", "#endif"])
    return "\n".join(lines) + "\n"


def _emit_linker_script(memory_map: dict[str, Any]) -> str:
    rom = memory_map["boot_rom"]
    sram = memory_map["sram"]
    return "\n".join(
        [
            "/* Generated by sw/tools/soc/emit_soc_spec.py from arch/configs/soc_v0.jsonc. */",
            "/* Do not edit by hand. */",
            "ENTRY(_start)",
            "",
            "MEMORY",
            "{",
            f"    ROM  (rx)  : ORIGIN = 0x{rom['base'] & 0xFFFF_FFFF:08x}, LENGTH = 0x{rom['size_bytes']:08x}",
            f"    SRAM (rwx) : ORIGIN = 0x{sram['base'] & 0xFFFF_FFFF:08x}, LENGTH = 0x{sram['size_bytes']:08x}",
            "}",
            "",
            "SECTIONS",
            "{",
            "    .text : {",
            "        KEEP(*(.text.start))",
            "        *(.text*)",
            "        *(.rodata*)",
            "    } > ROM",
            "",
            "    .data : {",
            "        *(.data*)",
            "    } > SRAM AT > ROM",
            "",
            "    .bss (NOLOAD) : {",
            "        *(.bss*)",
            "        *(COMMON)",
            "    } > SRAM",
            "}",
            "",
        ]
    )


def _mask_for_size(size: int) -> int:
    if size <= 0 or size & (size - 1):
        raise ValueError(f"region size must be a positive power of two: {size}")
    return (0x1_0000_0000 - size) & 0xFFFF_FFFF


def _validate_memory_map(memory_map: dict[str, Any]) -> None:
    for name, region in memory_map.items():
        base = int(region["base"])
        size = int(region["size_bytes"])
        if size <= 0 or size & (size - 1):
            raise ValueError(f"{name} size must be a positive power of two: {size}")
        if base % size != 0:
            raise ValueError(f"{name} base 0x{base:08x} must be aligned to size 0x{size:08x}")


def _read_jsonc(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    lines = [_strip_line_comment(line) for line in text.splitlines()]
    return json.loads("\n".join(lines))


def _strip_line_comment(line: str) -> str:
    in_string = False
    escaped = False
    for i in range(len(line) - 1):
        ch = line[i]
        if escaped:
            escaped = False
            continue
        if ch == "\\":
            escaped = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if not in_string and line[i : i + 2] == "//":
            return line[:i]
    return line


if __name__ == "__main__":
    main()
