"""Emit generated Transformer v1 config headers/packages from JSONC."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


DEFAULT_CONFIG = Path("arch/configs/npu_transformer_v1.jsonc")
DEFAULT_OUT_DIR = Path("build/generated")


def read_jsonc(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//.*$", "", text, flags=re.MULTILINE)
    return json.loads(text)


def extract_constants(config: dict[str, Any]) -> dict[str, int]:
    modules = config["modules"]
    vector = modules["vector_engine"]
    reduction = modules["reduction_engine"]
    sfu = modules["sfu"]
    encodings = config["primitive_op_encodings"]
    constants = {
        "CFG_VECTOR_LANES": int(vector["lanes"]),
        "CFG_VECTOR_DATA_WIDTH": int(vector["data_width"]),
        "CFG_REDUCTION_LANES": int(reduction["lanes"]),
        "CFG_REDUCTION_MAX_LEN": int(reduction["max_len"]),
        "CFG_REDUCTION_DATA_WIDTH": int(reduction["data_width"]),
        "CFG_REDUCTION_RESULT_WIDTH": int(reduction["result_width"]),
        "CFG_SFU_DATA_WIDTH": int(sfu["data_width"]),
        "CFG_SFU_EXP_INPUT_SCALE": int(sfu["exp_input_scale"]),
        "CFG_SFU_EXP_LUT_ENTRIES": int(sfu["exp_lut_entries"]),
        "CFG_SFU_EXP_OUTPUT_Q": int(sfu["exp_output_q"]),
        "CFG_SFU_RECIP_OUTPUT_Q": int(sfu["recip_output_q"]),
        "CFG_SFU_RSQRT_OUTPUT_Q": int(sfu["rsqrt_output_q"]),
    }
    for idx, value in enumerate(sfu["bringup_exp_q15_segments"]):
        constants[f"CFG_SFU_BRINGUP_EXP_SEG_{idx}"] = int(value)
    for name, value in encodings["vector"].items():
        constants[f"CFG_{name}"] = int(value)
    for name, value in encodings["reduction"].items():
        constants[f"CFG_{name}"] = int(value)
    for name, value in encodings["sfu"].items():
        constants[f"CFG_{name}"] = int(value)
    return constants


def emit_sv_package(constants: dict[str, int], source: Path) -> str:
    lines = [
        f"// Generated by sw/tools/transformer/emit_transformer_config.py from {source}.",
        "package npu_transformer_v1_config_pkg;",
    ]
    for name, value in constants.items():
        lines.append(f"    localparam int {name} = {value};")
    lines.append("endpackage")
    return "\n".join(lines) + "\n"


def emit_c_header(constants: dict[str, int], source: Path) -> str:
    lines = [
        f"/* Generated by sw/tools/transformer/emit_transformer_config.py from {source}. */",
        "#ifndef NPU_TRANSFORMER_V1_CONFIG_H",
        "#define NPU_TRANSFORMER_V1_CONFIG_H",
        "",
    ]
    for name, value in constants.items():
        lines.append(f"#define {name} {value}")
    lines.extend(["", "#endif"])
    return "\n".join(lines) + "\n"


def emit_python(constants: dict[str, int], source: Path) -> str:
    lines = [
        f"# Generated by sw/tools/transformer/emit_transformer_config.py from {source}.",
    ]
    for name, value in constants.items():
        lines.append(f"{name} = {value}")
    return "\n".join(lines) + "\n"


def emit(config_path: Path, out_dir: Path) -> dict[str, Path]:
    constants = extract_constants(read_jsonc(config_path))
    out_dir.mkdir(parents=True, exist_ok=True)
    outputs = {
        "sv": out_dir / "npu_transformer_v1_config_pkg.sv",
        "h": out_dir / "npu_transformer_v1_config.h",
        "py": out_dir / "npu_transformer_v1_config.py",
    }
    outputs["sv"].write_text(emit_sv_package(constants, config_path), encoding="utf-8")
    outputs["h"].write_text(emit_c_header(constants, config_path), encoding="utf-8")
    outputs["py"].write_text(emit_python(constants, config_path), encoding="utf-8")
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = parser.parse_args()
    outputs = emit(args.config, args.out_dir)
    for path in outputs.values():
        print(path)


if __name__ == "__main__":
    main()
