"""Emit generated headers from the NPU wrapper JSONC register map."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", type=Path, default=Path("arch/configs/npu_wrapper_v0.jsonc"))
    parser.add_argument("--svh-out", type=Path, default=Path("build/npu_wrapper/npu_v0_regs.svh"))
    parser.add_argument("--header-out", type=Path, default=Path("build/npu_wrapper/npu_v0_regs.h"))
    args = parser.parse_args()

    spec = _read_jsonc(args.spec)
    entries = _entries(spec)

    args.svh_out.parent.mkdir(parents=True, exist_ok=True)
    args.svh_out.write_text(_emit_svh(entries), encoding="utf-8")

    args.header_out.parent.mkdir(parents=True, exist_ok=True)
    args.header_out.write_text(_emit_header(entries), encoding="utf-8")


def _entries(spec: dict[str, Any]) -> list[tuple[str, int]]:
    entries: list[tuple[str, int]] = []
    for group_name in ("registers", "windows"):
        for name, item in spec[group_name].items():
            entries.append((f"NPU_OPSCHED_{name.upper()}", int(item["offset"])))
    return entries


def _emit_svh(entries: list[tuple[str, int]]) -> str:
    lines = [
        "// Generated by sw/tools/npu_wrapper/emit_npu_wrapper_spec.py.",
        "// Do not edit by hand.",
    ]
    max_name = max(len(name) for name, _value in entries)
    for name, value in entries:
        lines.append(f"localparam int {name:<{max_name}} = 12'h{value:03x};")
    return "\n".join(lines) + "\n"


def _emit_header(entries: list[tuple[str, int]]) -> str:
    lines = [
        "/* Generated by sw/tools/npu_wrapper/emit_npu_wrapper_spec.py. */",
        "/* Do not edit by hand. */",
        "#ifndef NPU_V0_REGS_H",
        "#define NPU_V0_REGS_H",
        "",
    ]
    max_name = max(len(name) for name, _value in entries)
    for name, value in entries:
        lines.append(f"#define {name:<{max_name}} 0x{value:03x}u")
    lines.extend(["", "#endif"])
    return "\n".join(lines) + "\n"


def _read_jsonc(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return json.loads("\n".join(_strip_line_comment(line) for line in text.splitlines()))


def _strip_line_comment(line: str) -> str:
    in_string = False
    escaped = False
    for i in range(len(line) - 1):
        ch = line[i]
        if escaped:
            escaped = False
            continue
        if ch == "\\":
            escaped = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if not in_string and line[i : i + 2] == "//":
            return line[:i]
    return line


if __name__ == "__main__":
    main()
