#!/usr/bin/env python3
"""Refresh architecture research references from public search endpoints.

The script intentionally uses only the Python standard library. It queries the
arXiv API for a small curated set of accelerator-architecture topics and writes
an annotated Markdown file that humans can review before promoting ideas into
the architecture spec.
"""

from __future__ import annotations

import argparse
import datetime as dt
import html
import re
import sys
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Iterable


DEFAULT_QUERIES = [
    "TPU architecture systolic array machine learning accelerator",
    "GPU tensor core architecture machine learning accelerator",
    "NPU architecture neural processing unit dataflow",
    "DNN accelerator scratchpad dataflow systolic array",
    "transformer accelerator architecture softmax matmul",
]

ARXIV_API = "https://export.arxiv.org/api/query"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="references/discovered_references.md")
    parser.add_argument("--max-results", type=int, default=5)
    parser.add_argument("--query", action="append", default=[])
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Write the query plan without performing network requests.",
    )
    args = parser.parse_args()

    queries = args.query or DEFAULT_QUERIES
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Discovered Architecture References",
        "",
        f"Generated at: {dt.datetime.utcnow().isoformat(timespec='seconds')}Z",
        "",
        "This file is generated by `scripts/refresh_references.py`. Review entries",
        "before copying durable notes into `architecture_references.md` or",
        "`candidate_ideas.md`.",
        "",
    ]

    if args.offline:
        lines.extend(["## Offline Query Plan", ""])
        for query in queries:
            lines.append(f"- {query}")
        output.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return 0

    for query in queries:
        lines.extend([f"## Query: {query}", ""])
        try:
            entries = list(search_arxiv(query, args.max_results))
        except Exception as exc:  # pragma: no cover - network path
            lines.append(f"- ERROR: {exc}")
            lines.append("")
            continue
        if not entries:
            lines.append("- No results")
        for entry in entries:
            lines.extend(
                [
                    f"### {entry['title']}",
                    "",
                    f"- Link: {entry['link']}",
                    f"- Published: {entry['published']}",
                    f"- Authors: {entry['authors']}",
                    f"- Summary: {entry['summary']}",
                    "- Project status: `candidate`",
                    "",
                ]
            )

    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


def search_arxiv(query: str, max_results: int) -> Iterable[dict[str, str]]:
    params = {
        "search_query": f"all:{query}",
        "start": "0",
        "max_results": str(max_results),
        "sortBy": "submittedDate",
        "sortOrder": "descending",
    }
    url = f"{ARXIV_API}?{urllib.parse.urlencode(params)}"
    with urllib.request.urlopen(url, timeout=20) as response:
        data = response.read()

    root = ET.fromstring(data)
    ns = {"atom": "http://www.w3.org/2005/Atom"}
    for entry in root.findall("atom:entry", ns):
        title = _clean(entry.findtext("atom:title", default="", namespaces=ns))
        summary = _clean(entry.findtext("atom:summary", default="", namespaces=ns))
        published = entry.findtext("atom:published", default="", namespaces=ns)[:10]
        authors = ", ".join(
            _clean(author.findtext("atom:name", default="", namespaces=ns))
            for author in entry.findall("atom:author", ns)
        )
        link = ""
        for link_node in entry.findall("atom:link", ns):
            if link_node.attrib.get("rel") == "alternate":
                link = link_node.attrib.get("href", "")
                break
        yield {
            "title": title,
            "summary": summary[:600],
            "published": published,
            "authors": authors,
            "link": link,
        }


def _clean(text: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(text)).strip()


if __name__ == "__main__":
    sys.exit(main())

