"""Emit C data arrays for the SoC CPU smoke firmware from RTL fixtures."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


_REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_REPO_ROOT / "sw" / "tools"))

from npu_phase0.digits_classifier import (  # noqa: E402
    CLASS_COLUMNS,
    REAL_CLASSES,
    classifier_inputs_from_image,
    lower_classifier_to_rtl_tiles,
    predict_label,
    reference_logits_from_image,
)
from npu_phase0.golden import matmul  # noqa: E402
from npu_compiler.k_stream import plan_matmul_k_stream  # noqa: E402
from npu_phase0.real_mnist_cnn import (  # noqa: E402
    MODEL_README_PATH,
    MODEL_WEIGHTS_PATH,
    TEST_IMAGES_PATH,
    TEST_LABELS_PATH,
    fc1_npu_inputs_from_flat,
    fc2_npu_inputs_from_activation,
    forward_intermediates,
    load_mnist_images,
    load_mnist_labels,
    load_safetensors_f32,
    lower_fc2_to_rtl_tiles,
    numpy_available,
    predict,
)
from transformer.generate_transformer_micro_fixtures import (  # noqa: E402
    generate_transformer_micro_fixtures,
)


DATASETS = (
    ("matmul_a", "matmul_a.hex"),
    ("matmul_b", "matmul_b.hex"),
    ("matmul_expected_c", "matmul_expected_c.hex"),
    ("matmul_program", "matmul_program.hex"),
    ("attention_scale_mask_program", "attention_scale_mask_program.hex"),
    ("attention_softmax_program", "attention_softmax_program.hex"),
    ("vector_tile_vadd_program", "vector_tile_vadd_program.hex"),
    ("vector_tile_rmsnorm_src0_program", "vector_tile_rmsnorm_src0_program.hex"),
    ("vector_tile_rmsnorm_src1_program", "vector_tile_rmsnorm_src1_program.hex"),
    ("vector_tile_gate_mul_program", "vector_tile_gate_mul_program.hex"),
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixtures", type=Path, default=Path("build/rtl_fixture"))
    parser.add_argument("--out", type=Path, default=Path("build/firmware/soc_cpu_smoke_data.h"))
    parser.add_argument("--manifest-out", type=Path, default=Path("build/ppa/data/workload_manifest.json"))
    parser.add_argument(
        "--workload-profile",
        choices=("quick", "transformer", "cnn-full", "all"),
        default="quick",
        help="Select optional workload groups for the soc_cpu_smoke firmware.",
    )
    args = parser.parse_args()

    lines = [
        "/* Generated by sw/tools/firmware/emit_soc_cpu_smoke_data.py. */",
        "/* Do not edit by hand. */",
        "#ifndef SOC_CPU_SMOKE_DATA_H",
        "#define SOC_CPU_SMOKE_DATA_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    for symbol, filename in DATASETS:
        values = _read_hex(args.fixtures / filename)
        lines.append(f"#define {symbol.upper()}_LEN {len(values)}u")
        lines.append(f"static const uint32_t {symbol}[{len(values)}] = {{")
        for value in values:
            lines.append(f"    0x{value & 0xFFFF_FFFF:08x}u,")
        lines.append("};")
        lines.append("")

    _append_vector_tile_smoke_data(lines)

    include_cnn = args.workload_profile in ("cnn-full", "all")
    include_transformer = args.workload_profile in ("quick", "transformer", "all")

    digits_jobs = _append_digits_classifier_data(lines)
    if include_cnn:
        fc1_tile_jobs = _append_real_mnist_cnn_fc1_tile_data(lines)
        fc1_k_stream_jobs = _append_real_mnist_cnn_fc1_k_stream_data(lines)
        fc1_full_jobs, fc1_full_k_chunks = _append_real_mnist_cnn_fc1_full_k_stream_data(lines)
        fc2_jobs = _append_real_mnist_cnn_fc2_data(lines)
    else:
        _append_real_mnist_cnn_disabled(lines)
        fc1_tile_jobs = 0
        fc1_k_stream_jobs = 0
        fc1_full_jobs = 0
        fc1_full_k_chunks = 0
        fc2_jobs = 0
    transformer_micro = _append_transformer_micro_data(lines) if include_transformer else _append_transformer_disabled(lines)
    jobs = _build_workload_jobs(
        digits_jobs,
        fc1_tile_jobs if fc2_jobs else 0,
        fc1_k_stream_jobs if fc2_jobs else 0,
        fc1_full_jobs if fc2_jobs else 0,
        fc2_jobs,
        transformer_micro["executable_workloads"],
    )
    _append_job_id_defines(lines, jobs)
    _append_transformer_runtime_plan_data(lines, transformer_micro)
    lines.append("#endif")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _write_workload_manifest(
        args.manifest_out,
        digits_jobs,
        fc1_tile_jobs if fc2_jobs else 0,
        fc1_k_stream_jobs if fc2_jobs else 0,
        fc1_full_jobs if fc2_jobs else 0,
        fc1_full_k_chunks if fc2_jobs else 0,
        fc2_jobs,
        transformer_micro,
        args.workload_profile,
        jobs,
    )


def _read_hex(path: Path) -> list[int]:
    return [int(line.strip(), 16) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _append_digits_classifier_data(lines: list[str]) -> int:
    image_path = _REPO_ROOT / "test/assets/digits_realistic/digit_2_gray.pgm"
    inputs = classifier_inputs_from_image(image_path)
    jobs = lower_classifier_to_rtl_tiles(inputs)
    logits = reference_logits_from_image(image_path)
    expected_label = predict_label(logits)

    lines.append("#define DIGITS_TILE_COUNT 16u")
    lines.append("#define DIGITS_TILE_WORDS 64u")
    lines.append(f"#define DIGITS_LOGITS_WORDS {len(logits) * len(logits[0])}u")
    lines.append(f"#define DIGITS_CLASS_COUNT {REAL_CLASSES}u")
    lines.append(f"#define DIGITS_CLASS_COLUMNS {CLASS_COLUMNS}u")
    lines.append(f"#define DIGITS_EXPECTED_LABEL {expected_label}u")
    lines.append("")

    _append_2d_array(lines, "digits_tile_n_offsets", [[job["n_offset"] for job in jobs]], bits=32)
    _append_2d_array(lines, "digits_tile_a", [job["inputs"]["A"] for job in jobs], bits=8)
    _append_2d_array(lines, "digits_tile_b", [job["inputs"]["B"] for job in jobs], bits=8)
    _append_flat_array(lines, "digits_expected_logits", _flatten(logits), bits=32)
    return len(jobs)


def _real_mnist_external_available() -> bool:
    return (
        numpy_available()
        and (_REPO_ROOT / MODEL_WEIGHTS_PATH).exists()
        and (_REPO_ROOT / MODEL_README_PATH).exists()
        and (_REPO_ROOT / TEST_IMAGES_PATH).exists()
        and (_REPO_ROOT / TEST_LABELS_PATH).exists()
    )


def _append_real_mnist_cnn_fc1_tile_data(lines: list[str]) -> int:
    if not _real_mnist_external_available():
        lines.append("#define REAL_MNIST_CNN_FC1_TILE_ENABLED 0u")
        lines.append("")
        return 0

    weights = load_safetensors_f32(_REPO_ROOT / MODEL_WEIGHTS_PATH)
    images = load_mnist_images(_REPO_ROOT / TEST_IMAGES_PATH)
    labels = load_mnist_labels(_REPO_ROOT / TEST_LABELS_PATH)
    sample_index = 0
    expected_label = int(labels[sample_index])
    original_prediction = predict(images[sample_index], weights)
    if original_prediction != expected_label:
        raise ValueError(f"MNIST sample {sample_index} predicts {original_prediction}, expected {expected_label}")

    intermediates = forward_intermediates(images[sample_index], weights)
    npu_inputs = fc1_npu_inputs_from_flat(intermediates["flat"], weights)
    plan = plan_matmul_k_stream(
        npu_inputs["A"],
        npu_inputs["W"],
        n_offset=0,
        max_chunks=1,
        require_nonzero=True,
    )
    chunk = plan["chunks"][0]

    lines.append("#define REAL_MNIST_CNN_FC1_TILE_ENABLED 1u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_TILE_SAMPLE_INDEX {sample_index}u")
    lines.append("#define REAL_MNIST_CNN_FC1_TILE_WORDS 64u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_TILE_K_OFFSET {chunk['k_offset']}u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_TILE_N_OFFSET {plan['n_offset']}u")
    lines.append("")

    _append_flat_array(lines, "real_mnist_cnn_fc1_tile_a", _flatten(chunk["a_tile"]), bits=8)
    _append_flat_array(lines, "real_mnist_cnn_fc1_tile_b", _flatten(chunk["b_tile"]), bits=8)
    _append_flat_array(lines, "real_mnist_cnn_fc1_tile_expected_c", _flatten(chunk["expected_tile"]), bits=32)
    return 1


def _append_real_mnist_cnn_fc1_k_stream_data(lines: list[str]) -> int:
    if not _real_mnist_external_available():
        lines.append("#define REAL_MNIST_CNN_FC1_K_STREAM_ENABLED 0u")
        lines.append("")
        return 0

    weights = load_safetensors_f32(_REPO_ROOT / MODEL_WEIGHTS_PATH)
    images = load_mnist_images(_REPO_ROOT / TEST_IMAGES_PATH)
    labels = load_mnist_labels(_REPO_ROOT / TEST_LABELS_PATH)
    sample_index = 0
    expected_label = int(labels[sample_index])
    original_prediction = predict(images[sample_index], weights)
    if original_prediction != expected_label:
        raise ValueError(f"MNIST sample {sample_index} predicts {original_prediction}, expected {expected_label}")

    intermediates = forward_intermediates(images[sample_index], weights)
    npu_inputs = fc1_npu_inputs_from_flat(intermediates["flat"], weights)
    plan = plan_matmul_k_stream(
        npu_inputs["A"],
        npu_inputs["W"],
        n_offset=0,
        max_chunks=4,
        require_nonzero=True,
    )

    lines.append("#define REAL_MNIST_CNN_FC1_K_STREAM_ENABLED 1u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_K_STREAM_SAMPLE_INDEX {sample_index}u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_K_STREAM_CHUNKS {plan['k_chunks']}u")
    lines.append("#define REAL_MNIST_CNN_FC1_K_STREAM_TILE_WORDS 64u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_K_STREAM_N_OFFSET {plan['n_offset']}u")
    lines.append("")

    _append_flat_array(lines, "real_mnist_cnn_fc1_k_stream_k_offsets", plan["k_offsets"], bits=32)
    _append_2d_array(lines, "real_mnist_cnn_fc1_k_stream_a", plan["a_stream"], bits=8)
    _append_2d_array(lines, "real_mnist_cnn_fc1_k_stream_b", plan["b_stream"], bits=8)
    _append_flat_array(lines, "real_mnist_cnn_fc1_k_stream_expected_c", _flatten(plan["expected_c"]), bits=32)
    return 1


def _append_real_mnist_cnn_fc1_full_k_stream_data(lines: list[str]) -> tuple[int, int]:
    if not _real_mnist_external_available():
        lines.append("#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_ENABLED 0u")
        lines.append("")
        return 0, 0

    weights = load_safetensors_f32(_REPO_ROOT / MODEL_WEIGHTS_PATH)
    images = load_mnist_images(_REPO_ROOT / TEST_IMAGES_PATH)
    labels = load_mnist_labels(_REPO_ROOT / TEST_LABELS_PATH)
    sample_index = 0
    expected_label = int(labels[sample_index])
    original_prediction = predict(images[sample_index], weights)
    if original_prediction != expected_label:
        raise ValueError(f"MNIST sample {sample_index} predicts {original_prediction}, expected {expected_label}")

    intermediates = forward_intermediates(images[sample_index], weights)
    npu_inputs = fc1_npu_inputs_from_flat(intermediates["flat"], weights)
    tile_n = 8
    tile_count = npu_inputs["padded_columns"] // tile_n
    plans = [
        plan_matmul_k_stream(npu_inputs["A"], npu_inputs["W"], n_offset=tile * tile_n)
        for tile in range(tile_count)
    ]
    first_plan = plans[0]

    lines.append("#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_ENABLED 1u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_SAMPLE_INDEX {sample_index}u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_TILE_COUNT {tile_count}u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_CHUNKS {first_plan['k_chunks']}u")
    lines.append("#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_TILE_WORDS 64u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_REAL_COLUMNS {npu_inputs['real_columns']}u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_PADDED_COLUMNS {npu_inputs['padded_columns']}u")
    lines.append("")

    _append_flat_array(lines, "real_mnist_cnn_fc1_full_k_stream_n_offsets", [plan["n_offset"] for plan in plans], bits=32)
    _append_flat_array(lines, "real_mnist_cnn_fc1_full_k_stream_k_offsets", first_plan["k_offsets"], bits=32)
    _append_2d_array(lines, "real_mnist_cnn_fc1_full_k_stream_a", first_plan["a_stream"], bits=8)
    _append_3d_array(lines, "real_mnist_cnn_fc1_full_k_stream_b", [plan["b_stream"] for plan in plans], bits=8)
    _append_2d_array(
        lines,
        "real_mnist_cnn_fc1_full_k_stream_expected_c",
        [plan["expected_c"] for plan in plans],
        bits=32,
    )
    return tile_count, first_plan["k_chunks"]


def _append_real_mnist_cnn_fc2_data(lines: list[str]) -> int:
    if not _real_mnist_external_available():
        lines.append("#define REAL_MNIST_CNN_FC2_ENABLED 0u")
        lines.append("")
        return 0

    weights = load_safetensors_f32(_REPO_ROOT / MODEL_WEIGHTS_PATH)
    images = load_mnist_images(_REPO_ROOT / TEST_IMAGES_PATH)
    labels = load_mnist_labels(_REPO_ROOT / TEST_LABELS_PATH)
    sample_index = 0
    expected_label = int(labels[sample_index])
    original_prediction = predict(images[sample_index], weights)
    if original_prediction != expected_label:
        raise ValueError(f"MNIST sample {sample_index} predicts {original_prediction}, expected {expected_label}")

    intermediates = forward_intermediates(images[sample_index], weights)
    npu_inputs = fc2_npu_inputs_from_activation(intermediates["fc1_relu"], weights)
    jobs = lower_fc2_to_rtl_tiles(npu_inputs)
    acc = matmul(npu_inputs["A"], npu_inputs["W"])
    bias_scale = npu_inputs["activation_scale"] * npu_inputs["weight_scale"]
    bias_scaled = [int(round(float(value) * bias_scale)) for value in npu_inputs["bias"]]
    scaled_logits = [int(acc[0][idx]) + bias_scaled[idx] for idx in range(REAL_CLASSES)]
    quantized_prediction = max(range(REAL_CLASSES), key=lambda idx: scaled_logits[idx])
    if quantized_prediction != expected_label:
        raise ValueError(
            f"quantized MNIST fc2 sample {sample_index} predicts {quantized_prediction}, expected {expected_label}"
        )

    lines.append("#define REAL_MNIST_CNN_FC2_ENABLED 1u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_SAMPLE_INDEX {sample_index}u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_TILE_COUNT {len(jobs)}u")
    lines.append("#define REAL_MNIST_CNN_FC2_TILE_WORDS 64u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_LOGITS_WORDS {len(acc) * len(acc[0])}u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_CLASS_COUNT {REAL_CLASSES}u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_CLASS_COLUMNS {CLASS_COLUMNS}u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_EXPECTED_LABEL {expected_label}u")
    lines.append("")

    _append_2d_array(lines, "real_mnist_cnn_fc2_tile_n_offsets", [[job["n_offset"] for job in jobs]], bits=32)
    _append_2d_array(lines, "real_mnist_cnn_fc2_tile_a", [job["inputs"]["A"] for job in jobs], bits=8)
    _append_2d_array(lines, "real_mnist_cnn_fc2_tile_b", [job["inputs"]["B"] for job in jobs], bits=8)
    _append_flat_array(lines, "real_mnist_cnn_fc2_bias_scaled", bias_scaled, bits=32)
    _append_flat_array(lines, "real_mnist_cnn_fc2_expected_scaled_logits", scaled_logits, bits=32)
    return len(jobs)


def _append_real_mnist_cnn_disabled(lines: list[str]) -> None:
    lines.append("#define REAL_MNIST_CNN_FC1_TILE_ENABLED 0u")
    lines.append("")
    lines.append("#define REAL_MNIST_CNN_FC1_K_STREAM_ENABLED 0u")
    lines.append("")
    lines.append("#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_ENABLED 0u")
    lines.append("")
    lines.append("#define REAL_MNIST_CNN_FC2_ENABLED 0u")
    lines.append("")


def _write_workload_manifest(
    path: Path,
    digits_jobs: int,
    fc1_tile_jobs: int,
    fc1_k_stream_jobs: int,
    fc1_full_jobs: int,
    fc1_full_k_chunks: int,
    fc2_jobs: int,
    transformer_micro: dict | None = None,
    workload_profile: str = "quick",
    jobs: list[dict] | None = None,
) -> None:
    if jobs is None:
        jobs = _build_workload_jobs(
            digits_jobs,
            fc1_tile_jobs,
            fc1_k_stream_jobs,
            fc1_full_jobs,
            fc2_jobs,
            transformer_micro["executable_workloads"] if transformer_micro else [],
        )
    transformer_micro = transformer_micro or {"executable_workloads": [], "model_only_workloads": []}
    transformer_metadata = {
        item["name"]: {"kind": item["kind"], "metadata": item["metadata"]}
        for item in transformer_micro["executable_workloads"]
    }
    transformer_metadata.update(
        {
            item["name"]: {"kind": item["kind"], "metadata": item["metadata"]}
            for item in transformer_micro["model_only_workloads"]
        }
    )
    manifest_id = f"soc_cpu_smoke_{workload_profile.replace('-', '_')}_v0"
    manifest = {
        "schema": "npu_workload_manifest_v0",
        "manifest_id": manifest_id,
        "run_name": "soc_cpu_smoke",
        "generated_by": "sw/tools/firmware/emit_soc_cpu_smoke_data.py",
        "workload_profile": workload_profile,
        "workload_metadata": {
            "operator_smoke_matmul": {"kind": "operator_smoke"},
            "digits_linear_classifier": {
                "kind": "model",
                "metadata": {
                    "input": "test/assets/digits_realistic/digit_2_gray.pgm",
                    "graph": "test/graphs/digits_classifier.json",
                    "tile_graph": "test/graphs/digits_classifier_rtl_tile.json",
                    "tile_jobs": digits_jobs,
                    "description": "8x8 grayscale digit image, tiled matmul regression with CPU-side accumulation",
                },
            },
            "real_mnist_cnn_fc1_tile0": {
                "kind": "model_layer_tile",
                "metadata": {"tile_jobs": fc1_tile_jobs},
            },
            "real_mnist_cnn_fc1_k_stream_smoke": {
                "kind": "model_layer_tile",
                "metadata": {"tile_jobs": fc1_k_stream_jobs},
            },
            "real_mnist_cnn_fc1_full_k_stream_layer": {
                "kind": "model_layer",
                "metadata": {
                    "tile_jobs": fc1_full_jobs,
                    "k_chunks": fc1_full_k_chunks,
                    "comparison_baseline": {
                        "id": "npu_v0_a2_serial_k_stream_proxy",
                        "cycles_per_job": 58784
                    },
                },
            },
            "real_mnist_cnn_fc2": {
                "kind": "model_layer",
                "metadata": {"tile_jobs": fc2_jobs},
            },
            **transformer_metadata,
        },
        "jobs": jobs,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def _build_workload_jobs(
    digits_jobs: int,
    fc1_tile_jobs: int,
    fc1_k_stream_jobs: int,
    fc1_full_jobs: int,
    fc2_jobs: int,
    transformer_workloads: list[dict] | None = None,
) -> list[dict]:
    jobs: list[dict] = []

    def add(workload: str, op: str, role: str, count: int, tiled: bool = False) -> None:
        for tile_id in range(count):
            item = {
                "job_id": len(jobs) + 1,
                "workload": workload,
                "op": op,
                "role": role,
            }
            if tiled:
                item["tile_id"] = tile_id
            jobs.append(item)

    add("operator_smoke_matmul", "matmul", "smoke", 1)
    add("operator_smoke_vector_tile_vadd", "desc_vector_tile_v1", "smoke", 1)
    add("digits_linear_classifier", "matmul", "regression", digits_jobs, tiled=True)
    add("real_mnist_cnn_fc1_tile0", "matmul", "regression", fc1_tile_jobs, tiled=True)
    add("real_mnist_cnn_fc1_k_stream_smoke", "matmul_k_stream", "regression", fc1_k_stream_jobs, tiled=True)
    add("real_mnist_cnn_fc1_full_k_stream_layer", "matmul_k_stream", "regression", fc1_full_jobs, tiled=True)
    add("real_mnist_cnn_fc2", "matmul", "regression", fc2_jobs, tiled=True)
    for workload in transformer_workloads or []:
        if workload["op"] == "block_attention_head_group":
            for job in workload["stage_jobs"]:
                jobs.append(
                    {
                        "job_id": len(jobs) + 1,
                        "workload": workload["name"],
                        "op": job["op"],
                        "role": workload["role"],
                        "tile_id": job["stage_job_index"],
                        "attention_head": job["head"],
                        "attention_stage": job["stage"],
                    }
                )
            continue
        job_op = {
            "block_matmul_k_stream_group": "matmul_k_stream",
            "block_desc_vector_tile_group": "desc_vector_tile_v1",
        }.get(workload["op"], workload["op"])
        add(workload["name"], job_op, workload["role"], len(workload.get("tile_jobs", [None])), tiled=True)
    return jobs


def _append_transformer_micro_data(lines: list[str]) -> dict:
    transformer_micro = generate_transformer_micro_fixtures()
    executable = transformer_micro["executable_workloads"]
    lines.append("#define TRANSFORMER_MICRO_ENABLED 1u")
    lines.append(f"#define TRANSFORMER_MICRO_EXECUTABLE_WORKLOADS {len(executable)}u")
    lines.append("")
    for workload in executable:
        macro = workload["name"].upper()
        if workload["op"] in ("matmul_k_stream", "matmul_u16s8_q15"):
            lines.append(f"#define {macro}_CHUNKS {workload['k_chunks']}u")
            lines.append(f"#define {macro}_TILE_WORDS {workload['tile_words']}u")
            lines.append("")
            _append_2d_array(lines, f"{workload['name']}_a", workload["a_stream"], bits=int(workload.get("a_bits", 8)))
            _append_2d_array(lines, f"{workload['name']}_b", workload["b_stream"], bits=8)
            _append_flat_array(lines, f"{workload['name']}_expected_c", workload["expected_c"], bits=32)
        elif workload["op"] == "block_matmul_k_stream_group":
            max_chunks = int(workload["max_k_chunks"])
            tile_words = int(workload["tile_words"])
            tile_jobs = workload["tile_jobs"]
            lines.append(f"#define {macro}_TILE_JOBS {len(tile_jobs)}u")
            lines.append(f"#define {macro}_MAX_CHUNKS {max_chunks}u")
            lines.append(f"#define {macro}_TILE_WORDS {tile_words}u")
            lines.append("")
            _append_flat_array(lines, f"{workload['name']}_k_chunks", [job["k_chunks"] for job in tile_jobs], bits=32)
            _append_3d_array(
                lines,
                f"{workload['name']}_a",
                [_pad_chunks(job["a_stream"], max_chunks, tile_words) for job in tile_jobs],
                bits=8,
            )
            _append_3d_array(
                lines,
                f"{workload['name']}_b",
                [_pad_chunks(job["b_stream"], max_chunks, tile_words) for job in tile_jobs],
                bits=8,
            )
            _append_2d_array(lines, f"{workload['name']}_expected_c", [job["expected_c"] for job in tile_jobs], bits=32)
        elif workload["op"] == "block_desc_vector_tile_group":
            tile_words = int(workload["tile_words"])
            tile_jobs = workload["tile_jobs"]
            lines.append(f"#define {macro}_TILE_JOBS {len(tile_jobs)}u")
            lines.append(f"#define {macro}_TILE_WORDS {tile_words}u")
            lines.append("")
            _append_2d_array(lines, f"{workload['name']}_input0", [job["input0"] for job in tile_jobs], bits=32)
            _append_2d_array(lines, f"{workload['name']}_input1", [job["input1"] for job in tile_jobs], bits=32)
            if any("program_select" in job for job in tile_jobs):
                select_values = [0 if job.get("program_select") == "src0" else 1 for job in tile_jobs]
                _append_flat_array(lines, f"{workload['name']}_program_select", select_values, bits=32)
            _append_2d_array(
                lines,
                f"{workload['name']}_expected_output",
                [job["expected_output"] for job in tile_jobs],
                bits=32,
            )
        elif workload["op"] == "block_attention_head_group":
            heads = workload["heads"]
            lines.append(f"#define {macro}_HEADS {len(heads)}u")
            lines.append(f"#define {macro}_STAGE_JOBS {len(workload['stage_jobs'])}u")
            lines.append(f"#define {macro}_TILE_WORDS {workload['tile_words']}u")
            lines.append(f"#define {macro}_MASK_WORDS {len(workload['row_mask_words'])}u")
            lines.append("")
            qk_jobs = [job for job in workload["stage_jobs"] if job["stage"] == "qk"]
            scale_jobs = [job for job in workload["stage_jobs"] if job["stage"] == "scale_mask"]
            softmax_jobs = [job for job in workload["stage_jobs"] if job["stage"] == "softmax"]
            pv_jobs = [job for job in workload["stage_jobs"] if job["stage"] == "pv"]
            _append_flat_array(lines, f"{workload['name']}_row_mask_words", workload["row_mask_words"], bits=32)
            _append_2d_array(lines, f"{workload['name']}_qk_a", [job["a_stream"][0] for job in qk_jobs], bits=8)
            _append_2d_array(lines, f"{workload['name']}_qk_b", [job["b_stream"][0] for job in qk_jobs], bits=8)
            _append_2d_array(lines, f"{workload['name']}_qk_expected", [job["expected_output"] for job in qk_jobs], bits=32)
            _append_2d_array(lines, f"{workload['name']}_scale_expected", [job["expected_output"] for job in scale_jobs], bits=32)
            _append_2d_array(lines, f"{workload['name']}_softmax_expected", [job["expected_output"] for job in softmax_jobs], bits=32)
            _append_2d_array(lines, f"{workload['name']}_pv_b", [job["b_stream"][0] for job in pv_jobs], bits=8)
            _append_2d_array(lines, f"{workload['name']}_pv_expected", [job["expected_output"] for job in pv_jobs], bits=32)
        elif workload["op"] == "attention_softmax_v1":
            lines.append(f"#define {macro}_X_WORDS {workload['x_words']}u")
            lines.append(f"#define {macro}_Y_WORDS {workload['y_words']}u")
            lines.append("")
            _append_flat_array(lines, f"{workload['name']}_x", workload["x"], bits=32)
            _append_flat_array(lines, f"{workload['name']}_expected_y", workload["expected_y"], bits=32)
        elif workload["op"] == "attention_scale_mask_v1":
            lines.append(f"#define {macro}_SCORE_WORDS {workload['score_words']}u")
            lines.append(f"#define {macro}_MASK_WORDS {len(workload['row_mask_words'])}u")
            lines.append("")
            _append_flat_array(lines, f"{workload['name']}_input_scores", workload["input_scores"], bits=32)
            _append_flat_array(lines, f"{workload['name']}_expected_scores", workload["expected_scores"], bits=32)
            _append_flat_array(lines, f"{workload['name']}_row_mask_words", workload["row_mask_words"], bits=32)
        else:
            raise ValueError(f"unsupported executable transformer op {workload['op']!r}")
    return transformer_micro


def _append_vector_tile_smoke_data(lines: list[str]) -> None:
    lhs = [1000 + lane for lane in range(8)]
    rhs = [-17 - lane for lane in range(8)]
    expected = [lhs[lane] + rhs[lane] for lane in range(8)]
    lines.append("#define VECTOR_TILE_VADD_WORDS 8u")
    lines.append("")
    _append_flat_array(lines, "vector_tile_vadd_lhs", lhs, bits=32)
    _append_flat_array(lines, "vector_tile_vadd_rhs", rhs, bits=32)
    _append_flat_array(lines, "vector_tile_vadd_expected", expected, bits=32)


def _append_transformer_disabled(lines: list[str]) -> dict:
    lines.append("#define TRANSFORMER_MICRO_ENABLED 0u")
    lines.append("#define TRANSFORMER_MICRO_EXECUTABLE_WORKLOADS 0u")
    lines.append("#define TRANSFORMER_ATTENTION_RUNTIME_JOBS 0u")
    lines.append("")
    return {"attention_plans": [], "executable_workloads": [], "model_only_workloads": []}


def _append_job_id_defines(lines: list[str], jobs: list[dict]) -> None:
    first_by_workload: dict[str, int] = {}
    for job in jobs:
        first_by_workload.setdefault(job["workload"], job["job_id"])
    lines.append("")
    lines.append("/* Descriptor job identity values also consumed by workload_manifest.json. */")
    for workload, first_id in first_by_workload.items():
        macro = workload.upper()
        suffix = "_BASE" if sum(job["workload"] == workload for job in jobs) > 1 else ""
        lines.append(f"#define JOB_ID_{macro}{suffix} {first_id}u")
    lines.append("")


def _append_transformer_runtime_plan_data(lines: list[str], transformer_micro: dict) -> None:
    plans = transformer_micro.get("attention_plans", [])
    if not plans:
        lines.append("#define TRANSFORMER_ATTENTION_RUNTIME_JOBS 0u")
        lines.append("")
        return
    if len(plans) != 1:
        raise ValueError("current firmware smoke supports one attention runtime plan")
    plan = plans[0]
    if plan.get("execution_state") != "executable":
        raise ValueError(
            f"firmware cannot emit non-executable attention plan {plan['attention_group']}: "
            f"{plan.get('execution_state')}"
        )
    jobs = plan["runtime_jobs"]
    lines.append("#define TRANSFORMER_RUNTIME_STAGE_QK 1u")
    lines.append("#define TRANSFORMER_RUNTIME_STAGE_SCALE_MASK 2u")
    lines.append("#define TRANSFORMER_RUNTIME_STAGE_SOFTMAX 3u")
    lines.append("#define TRANSFORMER_RUNTIME_STAGE_PV 4u")
    lines.append("#define TRANSFORMER_RUNTIME_CHECK_EXACT 1u")
    lines.append("#define TRANSFORMER_RUNTIME_CHECK_ABS_TOL 2u")
    lines.append(f"#define TRANSFORMER_ATTENTION_RUNTIME_JOBS {len(jobs)}u")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint32_t stage;")
    lines.append("    uint32_t op_type;")
    lines.append("    uint32_t job_id;")
    lines.append("    uint32_t check_policy;")
    lines.append("} transformer_runtime_job_t;")
    lines.append("")
    lines.append(
        f"static const transformer_runtime_job_t {plan['attention_group']}_runtime_jobs[{len(jobs)}] = {{"
    )
    for job in jobs:
        stage_macro = {
            "qk": "TRANSFORMER_RUNTIME_STAGE_QK",
            "scale_mask": "TRANSFORMER_RUNTIME_STAGE_SCALE_MASK",
            "softmax": "TRANSFORMER_RUNTIME_STAGE_SOFTMAX",
            "pv": "TRANSFORMER_RUNTIME_STAGE_PV",
        }[job["stage_id"]]
        op_macro = {
            "matmul_k_stream": "SOC_NPU_JOB_OP_MATMUL_K_STREAM",
            "attention_scale_mask_v1": "SOC_NPU_JOB_OP_ATTENTION_SCALE_MASK_V1",
            "attention_softmax_v1": "SOC_NPU_JOB_OP_ATTENTION_SOFTMAX_V1",
            "matmul_u16s8_q15": "SOC_NPU_JOB_OP_MATMUL_U16S8_Q15",
        }[job["descriptor_op"]]
        check_macro = {
            "exact": "TRANSFORMER_RUNTIME_CHECK_EXACT",
            "absolute_tolerance": "TRANSFORMER_RUNTIME_CHECK_ABS_TOL",
        }[job["check_policy"]]
        lines.append(f"    {{{stage_macro}, {op_macro}, {job['job_id_symbol']}, {check_macro}}},")
    lines.append("};")
    lines.append("")


def _append_2d_array(lines: list[str], symbol: str, values: list, bits: int) -> None:
    if symbol == "digits_tile_n_offsets":
        flat_rows = values
        row_len = len(values[0])
    else:
        flat_rows = [_flatten(item) for item in values]
        row_len = len(flat_rows[0])
    lines.append(f"static const uint32_t {symbol}[{len(flat_rows)}][{row_len}] = {{")
    mask = (1 << bits) - 1
    for row in flat_rows:
        lines.append("    {" + ", ".join(f"0x{(int(value) & mask):08x}u" for value in row) + "},")
    lines.append("};")
    lines.append("")


def _append_3d_array(lines: list[str], symbol: str, values: list, bits: int) -> None:
    flat_planes = [[_flatten(row) for row in plane] for plane in values]
    rows = len(flat_planes[0])
    cols = len(flat_planes[0][0])
    mask = (1 << bits) - 1
    lines.append(f"static const uint32_t {symbol}[{len(flat_planes)}][{rows}][{cols}] = {{")
    for plane in flat_planes:
        lines.append("    {")
        for row in plane:
            lines.append("        {" + ", ".join(f"0x{(int(value) & mask):08x}u" for value in row) + "},")
        lines.append("    },")
    lines.append("};")
    lines.append("")


def _pad_chunks(chunks: list[list[int]], max_chunks: int, tile_words: int) -> list[list[int]]:
    padded = [list(chunk) for chunk in chunks]
    while len(padded) < max_chunks:
        padded.append([0 for _ in range(tile_words)])
    return padded


def _append_flat_array(lines: list[str], symbol: str, values: list[int], bits: int) -> None:
    mask = (1 << bits) - 1
    lines.append(f"static const uint32_t {symbol}[{len(values)}] = {{")
    for value in values:
        lines.append(f"    0x{(int(value) & mask):08x}u,")
    lines.append("};")
    lines.append("")


def _flatten(value):
    out = []
    for item in value:
        if isinstance(item, list):
            out.extend(_flatten(item))
        else:
            out.append(item)
    return out


if __name__ == "__main__":
    main()
