"""Emit C data arrays for the SoC CPU smoke firmware from RTL fixtures."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


_REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_REPO_ROOT / "sw" / "tools"))

from npu_phase0.digits_classifier import (  # noqa: E402
    CLASS_COLUMNS,
    REAL_CLASSES,
    classifier_inputs_from_image,
    lower_classifier_to_rtl_tiles,
    predict_label,
    reference_logits_from_image,
)
from npu_phase0.golden import matmul  # noqa: E402
from npu_compiler.k_stream import plan_matmul_k_stream  # noqa: E402
from npu_phase0.real_mnist_cnn import (  # noqa: E402
    MODEL_README_PATH,
    MODEL_WEIGHTS_PATH,
    TEST_IMAGES_PATH,
    TEST_LABELS_PATH,
    fc1_npu_inputs_from_flat,
    fc2_npu_inputs_from_activation,
    forward_intermediates,
    load_mnist_images,
    load_mnist_labels,
    load_safetensors_f32,
    lower_fc2_to_rtl_tiles,
    numpy_available,
    predict,
)


DATASETS = (
    ("matmul_a", "matmul_a.hex"),
    ("matmul_b", "matmul_b.hex"),
    ("matmul_expected_c", "matmul_expected_c.hex"),
    ("matmul_program", "matmul_program.hex"),
    ("softmax_x", "softmax_x.hex"),
    ("softmax_expected_y", "softmax_expected_y.hex"),
    ("softmax_program", "softmax_program.hex"),
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixtures", type=Path, default=Path("build/rtl_fixture"))
    parser.add_argument("--out", type=Path, default=Path("build/firmware/soc_cpu_smoke_data.h"))
    args = parser.parse_args()

    lines = [
        "/* Generated by sw/tools/firmware/emit_soc_cpu_smoke_data.py. */",
        "/* Do not edit by hand. */",
        "#ifndef SOC_CPU_SMOKE_DATA_H",
        "#define SOC_CPU_SMOKE_DATA_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    for symbol, filename in DATASETS:
        values = _read_hex(args.fixtures / filename)
        lines.append(f"#define {symbol.upper()}_LEN {len(values)}u")
        lines.append(f"static const uint32_t {symbol}[{len(values)}] = {{")
        for value in values:
            lines.append(f"    0x{value & 0xFFFF_FFFF:08x}u,")
        lines.append("};")
        lines.append("")

    _append_digits_classifier_data(lines)
    _append_real_mnist_cnn_fc1_tile_data(lines)
    _append_real_mnist_cnn_fc1_k_stream_data(lines)
    _append_real_mnist_cnn_fc1_full_k_stream_data(lines)
    _append_real_mnist_cnn_fc2_data(lines)
    lines.append("#endif")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _read_hex(path: Path) -> list[int]:
    return [int(line.strip(), 16) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _append_digits_classifier_data(lines: list[str]) -> None:
    image_path = _REPO_ROOT / "test/assets/digits_realistic/digit_2_gray.pgm"
    inputs = classifier_inputs_from_image(image_path)
    jobs = lower_classifier_to_rtl_tiles(inputs)
    logits = reference_logits_from_image(image_path)
    expected_label = predict_label(logits)

    lines.append("#define DIGITS_TILE_COUNT 16u")
    lines.append("#define DIGITS_TILE_WORDS 64u")
    lines.append(f"#define DIGITS_LOGITS_WORDS {len(logits) * len(logits[0])}u")
    lines.append(f"#define DIGITS_CLASS_COUNT {REAL_CLASSES}u")
    lines.append(f"#define DIGITS_CLASS_COLUMNS {CLASS_COLUMNS}u")
    lines.append(f"#define DIGITS_EXPECTED_LABEL {expected_label}u")
    lines.append("")

    _append_2d_array(lines, "digits_tile_n_offsets", [[job["n_offset"] for job in jobs]], bits=32)
    _append_2d_array(lines, "digits_tile_a", [job["inputs"]["A"] for job in jobs], bits=8)
    _append_2d_array(lines, "digits_tile_b", [job["inputs"]["B"] for job in jobs], bits=8)
    _append_flat_array(lines, "digits_expected_logits", _flatten(logits), bits=32)


def _real_mnist_external_available() -> bool:
    return (
        numpy_available()
        and (_REPO_ROOT / MODEL_WEIGHTS_PATH).exists()
        and (_REPO_ROOT / MODEL_README_PATH).exists()
        and (_REPO_ROOT / TEST_IMAGES_PATH).exists()
        and (_REPO_ROOT / TEST_LABELS_PATH).exists()
    )


def _append_real_mnist_cnn_fc1_tile_data(lines: list[str]) -> None:
    if not _real_mnist_external_available():
        lines.append("#define REAL_MNIST_CNN_FC1_TILE_ENABLED 0u")
        lines.append("")
        return

    weights = load_safetensors_f32(_REPO_ROOT / MODEL_WEIGHTS_PATH)
    images = load_mnist_images(_REPO_ROOT / TEST_IMAGES_PATH)
    labels = load_mnist_labels(_REPO_ROOT / TEST_LABELS_PATH)
    sample_index = 0
    expected_label = int(labels[sample_index])
    original_prediction = predict(images[sample_index], weights)
    if original_prediction != expected_label:
        raise ValueError(f"MNIST sample {sample_index} predicts {original_prediction}, expected {expected_label}")

    intermediates = forward_intermediates(images[sample_index], weights)
    npu_inputs = fc1_npu_inputs_from_flat(intermediates["flat"], weights)
    plan = plan_matmul_k_stream(
        npu_inputs["A"],
        npu_inputs["W"],
        n_offset=0,
        max_chunks=1,
        require_nonzero=True,
    )
    chunk = plan["chunks"][0]

    lines.append("#define REAL_MNIST_CNN_FC1_TILE_ENABLED 1u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_TILE_SAMPLE_INDEX {sample_index}u")
    lines.append("#define REAL_MNIST_CNN_FC1_TILE_WORDS 64u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_TILE_K_OFFSET {chunk['k_offset']}u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_TILE_N_OFFSET {plan['n_offset']}u")
    lines.append("")

    _append_flat_array(lines, "real_mnist_cnn_fc1_tile_a", _flatten(chunk["a_tile"]), bits=8)
    _append_flat_array(lines, "real_mnist_cnn_fc1_tile_b", _flatten(chunk["b_tile"]), bits=8)
    _append_flat_array(lines, "real_mnist_cnn_fc1_tile_expected_c", _flatten(chunk["expected_tile"]), bits=32)


def _append_real_mnist_cnn_fc1_k_stream_data(lines: list[str]) -> None:
    if not _real_mnist_external_available():
        lines.append("#define REAL_MNIST_CNN_FC1_K_STREAM_ENABLED 0u")
        lines.append("")
        return

    weights = load_safetensors_f32(_REPO_ROOT / MODEL_WEIGHTS_PATH)
    images = load_mnist_images(_REPO_ROOT / TEST_IMAGES_PATH)
    labels = load_mnist_labels(_REPO_ROOT / TEST_LABELS_PATH)
    sample_index = 0
    expected_label = int(labels[sample_index])
    original_prediction = predict(images[sample_index], weights)
    if original_prediction != expected_label:
        raise ValueError(f"MNIST sample {sample_index} predicts {original_prediction}, expected {expected_label}")

    intermediates = forward_intermediates(images[sample_index], weights)
    npu_inputs = fc1_npu_inputs_from_flat(intermediates["flat"], weights)
    plan = plan_matmul_k_stream(
        npu_inputs["A"],
        npu_inputs["W"],
        n_offset=0,
        max_chunks=4,
        require_nonzero=True,
    )

    lines.append("#define REAL_MNIST_CNN_FC1_K_STREAM_ENABLED 1u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_K_STREAM_SAMPLE_INDEX {sample_index}u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_K_STREAM_CHUNKS {plan['k_chunks']}u")
    lines.append("#define REAL_MNIST_CNN_FC1_K_STREAM_TILE_WORDS 64u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_K_STREAM_N_OFFSET {plan['n_offset']}u")
    lines.append("")

    _append_flat_array(lines, "real_mnist_cnn_fc1_k_stream_k_offsets", plan["k_offsets"], bits=32)
    _append_2d_array(lines, "real_mnist_cnn_fc1_k_stream_a", plan["a_stream"], bits=8)
    _append_2d_array(lines, "real_mnist_cnn_fc1_k_stream_b", plan["b_stream"], bits=8)
    _append_flat_array(lines, "real_mnist_cnn_fc1_k_stream_expected_c", _flatten(plan["expected_c"]), bits=32)


def _append_real_mnist_cnn_fc1_full_k_stream_data(lines: list[str]) -> None:
    if not _real_mnist_external_available():
        lines.append("#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_ENABLED 0u")
        lines.append("")
        return

    weights = load_safetensors_f32(_REPO_ROOT / MODEL_WEIGHTS_PATH)
    images = load_mnist_images(_REPO_ROOT / TEST_IMAGES_PATH)
    labels = load_mnist_labels(_REPO_ROOT / TEST_LABELS_PATH)
    sample_index = 0
    expected_label = int(labels[sample_index])
    original_prediction = predict(images[sample_index], weights)
    if original_prediction != expected_label:
        raise ValueError(f"MNIST sample {sample_index} predicts {original_prediction}, expected {expected_label}")

    intermediates = forward_intermediates(images[sample_index], weights)
    npu_inputs = fc1_npu_inputs_from_flat(intermediates["flat"], weights)
    tile_n = 8
    tile_count = npu_inputs["padded_columns"] // tile_n
    plans = [
        plan_matmul_k_stream(npu_inputs["A"], npu_inputs["W"], n_offset=tile * tile_n)
        for tile in range(tile_count)
    ]
    first_plan = plans[0]

    lines.append("#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_ENABLED 1u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_SAMPLE_INDEX {sample_index}u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_TILE_COUNT {tile_count}u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_CHUNKS {first_plan['k_chunks']}u")
    lines.append("#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_TILE_WORDS 64u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_REAL_COLUMNS {npu_inputs['real_columns']}u")
    lines.append(f"#define REAL_MNIST_CNN_FC1_FULL_K_STREAM_PADDED_COLUMNS {npu_inputs['padded_columns']}u")
    lines.append("")

    _append_flat_array(lines, "real_mnist_cnn_fc1_full_k_stream_n_offsets", [plan["n_offset"] for plan in plans], bits=32)
    _append_flat_array(lines, "real_mnist_cnn_fc1_full_k_stream_k_offsets", first_plan["k_offsets"], bits=32)
    _append_2d_array(lines, "real_mnist_cnn_fc1_full_k_stream_a", first_plan["a_stream"], bits=8)
    _append_3d_array(lines, "real_mnist_cnn_fc1_full_k_stream_b", [plan["b_stream"] for plan in plans], bits=8)
    _append_2d_array(
        lines,
        "real_mnist_cnn_fc1_full_k_stream_expected_c",
        [plan["expected_c"] for plan in plans],
        bits=32,
    )


def _append_real_mnist_cnn_fc2_data(lines: list[str]) -> None:
    if not _real_mnist_external_available():
        lines.append("#define REAL_MNIST_CNN_FC2_ENABLED 0u")
        lines.append("")
        return

    weights = load_safetensors_f32(_REPO_ROOT / MODEL_WEIGHTS_PATH)
    images = load_mnist_images(_REPO_ROOT / TEST_IMAGES_PATH)
    labels = load_mnist_labels(_REPO_ROOT / TEST_LABELS_PATH)
    sample_index = 0
    expected_label = int(labels[sample_index])
    original_prediction = predict(images[sample_index], weights)
    if original_prediction != expected_label:
        raise ValueError(f"MNIST sample {sample_index} predicts {original_prediction}, expected {expected_label}")

    intermediates = forward_intermediates(images[sample_index], weights)
    npu_inputs = fc2_npu_inputs_from_activation(intermediates["fc1_relu"], weights)
    jobs = lower_fc2_to_rtl_tiles(npu_inputs)
    acc = matmul(npu_inputs["A"], npu_inputs["W"])
    bias_scale = npu_inputs["activation_scale"] * npu_inputs["weight_scale"]
    bias_scaled = [int(round(float(value) * bias_scale)) for value in npu_inputs["bias"]]
    scaled_logits = [int(acc[0][idx]) + bias_scaled[idx] for idx in range(REAL_CLASSES)]
    quantized_prediction = max(range(REAL_CLASSES), key=lambda idx: scaled_logits[idx])
    if quantized_prediction != expected_label:
        raise ValueError(
            f"quantized MNIST fc2 sample {sample_index} predicts {quantized_prediction}, expected {expected_label}"
        )

    lines.append("#define REAL_MNIST_CNN_FC2_ENABLED 1u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_SAMPLE_INDEX {sample_index}u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_TILE_COUNT {len(jobs)}u")
    lines.append("#define REAL_MNIST_CNN_FC2_TILE_WORDS 64u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_LOGITS_WORDS {len(acc) * len(acc[0])}u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_CLASS_COUNT {REAL_CLASSES}u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_CLASS_COLUMNS {CLASS_COLUMNS}u")
    lines.append(f"#define REAL_MNIST_CNN_FC2_EXPECTED_LABEL {expected_label}u")
    lines.append("")

    _append_2d_array(lines, "real_mnist_cnn_fc2_tile_n_offsets", [[job["n_offset"] for job in jobs]], bits=32)
    _append_2d_array(lines, "real_mnist_cnn_fc2_tile_a", [job["inputs"]["A"] for job in jobs], bits=8)
    _append_2d_array(lines, "real_mnist_cnn_fc2_tile_b", [job["inputs"]["B"] for job in jobs], bits=8)
    _append_flat_array(lines, "real_mnist_cnn_fc2_bias_scaled", bias_scaled, bits=32)
    _append_flat_array(lines, "real_mnist_cnn_fc2_expected_scaled_logits", scaled_logits, bits=32)


def _append_2d_array(lines: list[str], symbol: str, values: list, bits: int) -> None:
    if symbol == "digits_tile_n_offsets":
        flat_rows = values
        row_len = len(values[0])
    else:
        flat_rows = [_flatten(item) for item in values]
        row_len = len(flat_rows[0])
    lines.append(f"static const uint32_t {symbol}[{len(flat_rows)}][{row_len}] = {{")
    mask = (1 << bits) - 1
    for row in flat_rows:
        lines.append("    {" + ", ".join(f"0x{(int(value) & mask):08x}u" for value in row) + "},")
    lines.append("};")
    lines.append("")


def _append_3d_array(lines: list[str], symbol: str, values: list, bits: int) -> None:
    flat_planes = [[_flatten(row) for row in plane] for plane in values]
    rows = len(flat_planes[0])
    cols = len(flat_planes[0][0])
    mask = (1 << bits) - 1
    lines.append(f"static const uint32_t {symbol}[{len(flat_planes)}][{rows}][{cols}] = {{")
    for plane in flat_planes:
        lines.append("    {")
        for row in plane:
            lines.append("        {" + ", ".join(f"0x{(int(value) & mask):08x}u" for value in row) + "},")
        lines.append("    },")
    lines.append("};")
    lines.append("")


def _append_flat_array(lines: list[str], symbol: str, values: list[int], bits: int) -> None:
    mask = (1 << bits) - 1
    lines.append(f"static const uint32_t {symbol}[{len(values)}] = {{")
    for value in values:
        lines.append(f"    0x{(int(value) & mask):08x}u,")
    lines.append("};")
    lines.append("")


def _flatten(value):
    out = []
    for item in value:
        if isinstance(item, list):
            out.extend(_flatten(item))
        else:
            out.append(item)
    return out


if __name__ == "__main__":
    main()
