"""Emit a tiny RV32I firmware image for the PicoRV32 SoC smoke test."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


X0 = 0
T0 = 5
T1 = 6
T2 = 7
S0 = 8


class Program:
    def __init__(self) -> None:
        self.items: list[tuple[str, str | int, tuple[int, ...], str]] = []

    def label(self, name: str) -> None:
        self.items.append(("label", name, (), f"{name}:"))

    def insn(self, word: int, asm: str) -> None:
        self.items.append(("insn", word & 0xFFFF_FFFF, (), f"    {asm}"))

    def branch(self, kind: str, rs1: int, rs2: int, label: str) -> None:
        self.items.append((kind, label, (rs1, rs2), f"    {kind} {_reg(rs1)}, {_reg(rs2)}, {label}"))

    def jal(self, label: str) -> None:
        self.items.append(("jal", label, (), f"    j {label}"))

    def comment(self, text: str) -> None:
        self.items.append(("comment", text, (), f"    # {text}"))

    def emit(self) -> list[int]:
        labels: dict[str, int] = {}
        pc = 0
        for kind, value, _args, _asm in self.items:
            if kind == "label":
                labels[str(value)] = pc
            elif kind != "comment":
                pc += 4

        words: list[int] = []
        pc = 0
        for kind, value, args, _asm in self.items:
            if kind in {"label", "comment"}:
                continue
            if kind == "insn":
                words.append(int(value))
            elif kind in {"beq", "bne"}:
                rs1, rs2 = args
                words.append(_branch(kind, rs1, rs2, labels[str(value)] - pc))
            elif kind == "jal":
                words.append(_jal(X0, labels[str(value)] - pc))
            else:
                raise ValueError(f"unknown item kind {kind!r}")
            pc += 4
        return words

    def asm(self) -> str:
        lines = [
            "/* Generated by sw/tools/firmware/emit_soc_cpu_smoke.py. */",
            "/* This file mirrors the boot ROM hex used by cpu-soc-sim. */",
            "    .section .text",
            "    .globl _start",
            "_start:",
        ]
        for kind, _value, _args, asm in self.items:
            if kind == "label" and asm == "_start:":
                continue
            lines.append(asm)
        return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--soc", type=Path, default=Path("arch/configs/soc_v0.jsonc"))
    parser.add_argument("--wrapper", type=Path, default=Path("arch/configs/npu_wrapper_v0.jsonc"))
    parser.add_argument("--fixtures", type=Path, default=Path("build/rtl_fixture"))
    parser.add_argument("--out", type=Path, default=Path("build/firmware/soc_cpu_smoke.hex"))
    parser.add_argument("--asm-out", type=Path, default=Path("build/firmware/soc_cpu_smoke.S"))
    parser.add_argument("--rom-words", type=int, default=8192)
    args = parser.parse_args()

    fixtures = args.fixtures
    soc_spec = _read_jsonc(args.soc)
    wrapper_spec = _read_jsonc(args.wrapper)
    npu_wrapper_base = soc_spec["memory_map"]["npu_wrapper"]["base"]
    test_status_base = soc_spec["memory_map"]["test_status"]["base"]
    wrapper_offsets = _wrapper_offsets(wrapper_spec)
    npu_wrapper = {
        "ctrl": npu_wrapper_base + wrapper_offsets["ctrl"],
        "status": npu_wrapper_base + wrapper_offsets["status"],
        "a": npu_wrapper_base + wrapper_offsets["a_base"],
        "b": npu_wrapper_base + wrapper_offsets["b_base"],
        "c": npu_wrapper_base + wrapper_offsets["c_base"],
        "x": npu_wrapper_base + wrapper_offsets["x_base"],
        "y": npu_wrapper_base + wrapper_offsets["y_base"],
        "program": npu_wrapper_base + wrapper_offsets["program_base"],
    }
    program = Program()

    program.comment("Load matmul inputs and program into the NPU wrapper windows.")
    _write_words(program, npu_wrapper["a"], _read_hex(fixtures / "matmul_a.hex"))
    _write_words(program, npu_wrapper["b"], _read_hex(fixtures / "matmul_b.hex"))
    _write_words(program, npu_wrapper["program"], _read_hex(fixtures / "matmul_program.hex"))
    program.comment("Start matmul and wait for STATUS.done.")
    _run_npu(program, npu_wrapper["ctrl"], npu_wrapper["status"], "wait_matmul")
    program.comment("Check Matrix C against generated expected values.")
    _check_words(program, npu_wrapper["c"], _read_hex(fixtures / "matmul_expected_c.hex"), "fail")

    program.comment("Load softmax input and program into the NPU wrapper windows.")
    _write_words(program, npu_wrapper["x"], _read_hex(fixtures / "softmax_x.hex"))
    _write_words(program, npu_wrapper["program"], _read_hex(fixtures / "softmax_program.hex"))
    program.comment("Start softmax and wait for STATUS.done.")
    _run_npu(program, npu_wrapper["ctrl"], npu_wrapper["status"], "wait_softmax")
    program.comment("Check Softmax Y against generated expected values.")
    _check_low_bytes(program, npu_wrapper["y"], _read_hex(fixtures / "softmax_expected_y.hex"), "fail")

    program.comment("Report PASS to the simulation-visible test status register.")
    _write_word(program, test_status_base, 0x0000_0001)
    program.label("pass")
    program.jal("pass")

    program.label("fail")
    program.comment("Report FAIL to the simulation-visible test status register.")
    _write_word(program, test_status_base, 0xFFFF_FFFF)
    program.label("fail_loop")
    program.jal("fail_loop")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    words = program.emit()
    if len(words) > args.rom_words:
        raise ValueError(f"firmware has {len(words)} words, exceeds ROM depth {args.rom_words}")
    words = words + [0] * (args.rom_words - len(words))

    with args.out.open("w", encoding="utf-8") as f:
        for word in words:
            f.write(f"{word:08x}\n")

    args.asm_out.parent.mkdir(parents=True, exist_ok=True)
    args.asm_out.write_text(program.asm(), encoding="utf-8")


def _read_hex(path: Path) -> list[int]:
    return [int(line.strip(), 16) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _read_jsonc(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return json.loads("\n".join(_strip_line_comment(line) for line in text.splitlines()))


def _wrapper_offsets(spec: dict[str, Any]) -> dict[str, int]:
    offsets = {name: int(item["offset"]) for name, item in spec["registers"].items()}
    offsets.update({name: int(item["offset"]) for name, item in spec["windows"].items()})
    return offsets


def _strip_line_comment(line: str) -> str:
    in_string = False
    escaped = False
    for i in range(len(line) - 1):
        ch = line[i]
        if escaped:
            escaped = False
            continue
        if ch == "\\":
            escaped = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if not in_string and line[i : i + 2] == "//":
            return line[:i]
    return line


def _write_words(program: Program, base: int, values: list[int]) -> None:
    _li(program, S0, base)
    for idx, value in enumerate(values):
        _li(program, T0, value)
        program.insn(_sw(T0, idx * 4, S0), f"sw {_reg(T0)}, {idx * 4}({_reg(S0)})")


def _write_word(program: Program, addr: int, value: int) -> None:
    _li(program, S0, addr)
    _li(program, T0, value)
    program.insn(_sw(T0, 0, S0), f"sw {_reg(T0)}, 0({_reg(S0)})")


def _run_npu(program: Program, ctrl_addr: int, status_addr: int, wait_label: str) -> None:
    _write_word(program, ctrl_addr, 1)
    _li(program, S0, status_addr)
    program.label(wait_label)
    program.insn(_lw(T0, 0, S0), f"lw {_reg(T0)}, 0({_reg(S0)})")
    program.insn(_andi(T0, T0, 1), f"andi {_reg(T0)}, {_reg(T0)}, 1")
    program.branch("beq", T0, X0, wait_label)


def _check_words(program: Program, base: int, expected: list[int], fail_label: str) -> None:
    _li(program, S0, base)
    for idx, value in enumerate(expected):
        program.insn(_lw(T0, idx * 4, S0), f"lw {_reg(T0)}, {idx * 4}({_reg(S0)})")
        _li(program, T1, value)
        _bne_far(program, T0, T1, fail_label, f"check_word_{idx}")


def _check_low_bytes(program: Program, base: int, expected: list[int], fail_label: str) -> None:
    _li(program, S0, base)
    for idx, value in enumerate(expected):
        program.insn(_lw(T0, idx * 4, S0), f"lw {_reg(T0)}, {idx * 4}({_reg(S0)})")
        program.insn(_andi(T0, T0, 0xFF), f"andi {_reg(T0)}, {_reg(T0)}, 255")
        _li(program, T1, value & 0xFF)
        _bne_far(program, T0, T1, fail_label, f"check_byte_{idx}")


def _bne_far(program: Program, rs1: int, rs2: int, fail_label: str, prefix: str) -> None:
    ok_label = f"{prefix}_ok"
    program.branch("beq", rs1, rs2, ok_label)
    program.jal(fail_label)
    program.label(ok_label)


def _li(program: Program, rd: int, value: int) -> None:
    value &= 0xFFFF_FFFF
    signed_value = value if value < 0x8000_0000 else value - 0x1_0000_0000
    if -2048 <= signed_value <= 2047:
        program.insn(_addi(rd, X0, signed_value), f"addi {_reg(rd)}, zero, {signed_value}")
        return

    upper = (value + 0x800) >> 12
    lower = value - (upper << 12)
    if lower >= 2048:
        lower -= 4096
    program.insn(_lui(rd, upper & 0xFFFFF), f"lui {_reg(rd)}, 0x{upper & 0xFFFFF:x}")
    if lower:
        program.insn(_addi(rd, rd, lower), f"addi {_reg(rd)}, {_reg(rd)}, {lower}")


def _reg(index: int) -> str:
    names = {
        0: "zero",
        5: "t0",
        6: "t1",
        7: "t2",
        8: "s0",
    }
    return names.get(index, f"x{index}")


def _lui(rd: int, imm20: int) -> int:
    return ((imm20 & 0xFFFFF) << 12) | (rd << 7) | 0x37


def _addi(rd: int, rs1: int, imm: int) -> int:
    return _itype(imm, rs1, 0b000, rd, 0x13)


def _andi(rd: int, rs1: int, imm: int) -> int:
    return _itype(imm, rs1, 0b111, rd, 0x13)


def _lw(rd: int, imm: int, rs1: int) -> int:
    return _itype(imm, rs1, 0b010, rd, 0x03)


def _sw(rs2: int, imm: int, rs1: int) -> int:
    imm &= 0xFFF
    return ((imm >> 5) << 25) | (rs2 << 20) | (rs1 << 15) | (0b010 << 12) | ((imm & 0x1F) << 7) | 0x23


def _itype(imm: int, rs1: int, funct3: int, rd: int, opcode: int) -> int:
    return ((imm & 0xFFF) << 20) | (rs1 << 15) | (funct3 << 12) | (rd << 7) | opcode


def _branch(kind: str, rs1: int, rs2: int, offset: int) -> int:
    if offset % 2:
        raise ValueError(f"branch offset must be 2-byte aligned: {offset}")
    funct3 = 0b000 if kind == "beq" else 0b001
    imm = offset & 0x1FFF
    return (
        (((imm >> 12) & 0x1) << 31)
        | (((imm >> 5) & 0x3F) << 25)
        | (rs2 << 20)
        | (rs1 << 15)
        | (funct3 << 12)
        | (((imm >> 1) & 0xF) << 8)
        | (((imm >> 11) & 0x1) << 7)
        | 0x63
    )


def _jal(rd: int, offset: int) -> int:
    if offset % 2:
        raise ValueError(f"jal offset must be 2-byte aligned: {offset}")
    imm = offset & 0x1F_FFFF
    return (
        (((imm >> 20) & 0x1) << 31)
        | (((imm >> 1) & 0x3FF) << 21)
        | (((imm >> 11) & 0x1) << 20)
        | (((imm >> 12) & 0xFF) << 12)
        | (rd << 7)
        | 0x6F
    )


if __name__ == "__main__":
    main()
